//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "UIAlertViewDelegate-Protocol.h"

@class BrandServiceContinueLocationReportLogic, NSString;

@interface BrandLocationReportLogicAlertOberserver : NSObject <UIAlertViewDelegate>
{
    BrandServiceContinueLocationReportLogic *weakReportLogic;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (void)askIsAllowReportLocation:(id)arg1;
@property(nonatomic) __weak BrandServiceContinueLocationReportLogic *weakReportLogic; // @synthesize weakReportLogic;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

