//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MMCommon/MMObject.h>

#import "IContactMgrExt-Protocol.h"
#import "PBMessageObserverDelegate-Protocol.h"
#import "UIAlertViewDelegate-Protocol.h"
#import "WCActionSheetDelegate-Protocol.h"
#import "contactVerifyLogicDelegate-Protocol.h"

@class CContact, MMHDHeadImageView, MMHeadImageView, MMLoadingView, NSString, UILabel, UIView;
@protocol ContactInfoAssistDelegate;

@interface CBaseContactInfoAssist : MMObject <contactVerifyLogicDelegate, IContactMgrExt, WCActionSheetDelegate, UIAlertViewDelegate, PBMessageObserverDelegate>
{
    UIView *m_headerView;
    UIView *m_footerView;
    MMHeadImageView *m_headView;
    MMHDHeadImageView *m_HDHeadView;
    MMLoadingView *m_loadingView;
    CContact *m_contact;
    UILabel *m_displayNameLabel;
    UILabel *m_userNameLabel;
    id <ContactInfoAssistDelegate> m_delegate;
}

- (void).cxx_destruct;
- (id)GetFloatView;
- (id)GetTableView;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (void)addContactInternal;
- (void)baseViewWillBePoped;
- (void)contactVerifyOk:(id)arg1 opCode:(unsigned int)arg2;
- (void)dealloc;
- (double)getSignatureWidth;
- (id)getUserNameCol;
- (void)handleAddedContact;
- (double)heightForPluginIntroCell:(id)arg1;
- (id)init;
- (void)initLoadingView;
- (void)initNickNameLabel;
- (void)initUserNameLabel;
- (_Bool)isInMyContactList;
@property(retain, nonatomic) CContact *m_contact; // @synthesize m_contact;
@property(nonatomic) __weak id <ContactInfoAssistDelegate> m_delegate; // @synthesize m_delegate;
@property(retain, nonatomic) MMHeadImageView *m_headView; // @synthesize m_headView;
- (void)makeContactIntroCell:(id)arg1 text:(id)arg2;
- (void)onAddToContacts;
- (void)onContactUpdated;
- (void)onContactVerifyFillVerifyMsg:(id)arg1;
- (void)opShareMyFriend;
- (void)profileDestory;
- (void)reloadTableView;
- (void)reloadView;
- (void)stopLoading;
- (void)updateFooterView;
- (void)updateInstallStateAndReloadTableView;
- (void)updateNickNameLabel;
- (void)verifyContactWithOpCode:(unsigned int)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

