//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface CdnTimelineMediaOfSightInfo : NSObject
{
    NSString *m_nsClientMsgID;
    NSString *m_nsFilePath;
    _Bool m_bHaveThumb;
    NSString *m_nsThumbFilePath;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool m_bHaveThumb; // @synthesize m_bHaveThumb;
@property(retain, nonatomic) NSString *m_nsClientMsgID; // @synthesize m_nsClientMsgID;
@property(retain, nonatomic) NSString *m_nsFilePath; // @synthesize m_nsFilePath;
@property(retain, nonatomic) NSString *m_nsThumbFilePath; // @synthesize m_nsThumbFilePath;

@end

