//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MMCommon/MMService.h>

#import "MMService-Protocol.h"

@class NSMutableArray, NSObject, NSString;
@protocol OS_dispatch_queue;

@interface ClearDataMgr : MMService <MMService>
{
    NSMutableArray *_arrSessionInfo;
    unsigned long long _startLoadDataTime;
    unsigned int _loadDataCostTime;
    unsigned long long _fileSizeOver3Month;
    long long _nowTime;
    vector_91fc892d _arrSessionItems;
    vector_3d478e4e _arrDataItems;
    vector_91fc892d _arrImageSessionItems;
    vector_91fc892d _arrVideoSessionItems;
    vector_3d478e4e _arrFileItems;
    NSObject<OS_dispatch_queue> *_removeFileQueue;
    _Bool _loadingData;
    _Bool _loadDataEnd;
    unsigned long long _allSessionSize;
    map_1b8cc407 _sizeOfFileType;
}

- (id).cxx_construct;
- (void).cxx_destruct;
@property(readonly, nonatomic) unsigned long long allSessionSize; // @synthesize allSessionSize=_allSessionSize;
- (void)cleanCache;
- (void)deleteDataInSession:(const vector_3d478e4e *)arg1;
- (void)deleteFileData:(const vector_3d478e4e *)arg1;
- (void)deleteFilesOver3Month;
- (void)deleteImageSessionsAndKeepMessage:(const vector_91fc892d *)arg1;
- (void)deleteSessions:(const vector_91fc892d *)arg1;
- (void)deleteSessionsAndKeepMessage:(const vector_91fc892d *)arg1;
- (void)deleteVideoSessionsAndKeepMessage:(const vector_91fc892d *)arg1;
- (void)doCleanCache;
- (void)doDeleteFilesOver3Month;
- (const vector_91fc892d *)getAllSessionItem;
- (unsigned long long)getCountOfDataItem;
- (unsigned long long)getCountOfFileItem;
- (unsigned long long)getCountOfImageSessionItem;
- (unsigned long long)getCountOfSessionItem;
- (unsigned long long)getCountOfVideoSessionItem;
- (shared_ptr_f9ca816a)getDataItemOfIndex:(unsigned long long)arg1;
- (void)getDetailInfoForSessionInfo:(id)arg1;
- (const vector_3d478e4e *)getFileDataItem;
- (shared_ptr_f9ca816a)getFileItemOfIndex:(unsigned long long)arg1;
- (unsigned long long)getFileSizeOver3Month;
- (const vector_91fc892d *)getImageSessionItem;
- (shared_ptr_174ad120)getImageSessionItemOfIndex:(unsigned long long)arg1;
- (unsigned int)getLoadDataCostTime;
- (shared_ptr_174ad120)getSessionItemOfIndex:(unsigned long long)arg1;
- (id)getSessionName:(id)arg1;
- (const vector_91fc892d *)getVideoSessionItem;
- (shared_ptr_174ad120)getVideoSessionItemOfIndex:(unsigned long long)arg1;
- (id)init;
- (void)innerDeleteDataItem:(struct ClearDataItem *)arg1;
- (_Bool)isDataLoadEnd;
- (void)onLoadData;
- (unsigned int)parseMesLocalIdFromPath:(id)arg1;
- (void)preInnerDeleteDataItems:(const vector_3d478e4e *)arg1;
- (void)preInnerDeleteSessionDataItems:(const vector_91fc892d *)arg1;
- (void)reportBiz:(unsigned int)arg1 cleanedSize:(unsigned long long)arg2;
@property(readonly, nonatomic) map_1b8cc407 sizeOfFileType; // @synthesize sizeOfFileType=_sizeOfFileType;
- (void)startLoadData;
- (void)stopLoadData;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

