//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PluginContactInfoAssist.h"

#import "MessageObserverDelegate-Protocol.h"
#import "UIAlertViewDelegate-Protocol.h"

@class NSString, UIAlertView;

@interface CPushMailContactInfoAssist : PluginContactInfoAssist <MessageObserverDelegate, UIAlertViewDelegate>
{
    map_490096f0 m_mapPushMailCellToCellType;
    UIAlertView *m_pwdAlertView;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)MessageReturn:(unsigned int)arg1 MessageInfo:(id)arg2 Event:(unsigned int)arg3;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)dealloc;
- (void)doSwitchPushMail:(id)arg1;
- (void)doSwitchPushMailByAlertView:(id)arg1;
- (id)getLoadingText;
- (id)getPluginIntro;
- (id)getPushMailErrorTitle;
- (void)handleSwitchPushMailOk;
- (void)installPlugin;
- (_Bool)isShowOpenPushMailBtn;
- (void)onSendPushMailPwd:(id)arg1;
- (void)onSwitchViewOff;
- (void)onSwitchViewOn;
- (void)onWrite;
- (void)reloadInstalledTableViewData;
- (void)reloadPushMailTableView;
- (void)showClosePushMailAlert;
- (void)showFolderConfigPage;
- (void)showInputPwdAlert:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

