//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class WCTDatabase, WCTTable;

@interface EnterpriseBrandAttrDB : NSObject
{
    WCTDatabase *_db;
    WCTTable *_table;
}

- (void).cxx_destruct;
- (void)closeDB;
- (void)dealloc;
- (_Bool)deleteAttrByUserName:(id)arg1;
- (id)getAttrByUserName:(id)arg1;
- (id)initWithPath:(id)arg1;
- (_Bool)setAttr:(id)arg1 onProperties:(const list_2812bee2 *)arg2;

@end

