//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MMCommon/MMObject.h>

#import "IFavoritesExt-Protocol.h"
#import "MMTipsViewControllerDelegate-Protocol.h"
#import "MMToastViewControllerDelegate-Protocol.h"
#import "UIAlertViewDelegate-Protocol.h"

@class MMTipsViewController, MMToastViewController, NSString;

@interface FavAddItemHelper : MMObject <IFavoritesExt, MMTipsViewControllerDelegate, MMToastViewControllerDelegate, UIAlertViewDelegate>
{
    MMToastViewController *m_toastView;
    MMTipsViewController *m_favIntroView;
    _Bool isUsing;
    _Bool _shouldRestoreMainwindow;
}

+ (void)freeFavAddHelper;
+ (id)getFavAddHelper;
- (void).cxx_destruct;
- (void)addFavItem:(id)arg1;
- (void)addFavItem:(id)arg1 withTipWording:(id)arg2;
- (_Bool)addFavItemButShowCapacityTip:(id)arg1;
- (_Bool)addFavItemButShowExpireOrBigFileTip:(id)arg1;
- (_Bool)addFavItemButShowWarningTip:(id)arg1 withTip:(id)arg2;
- (void)addFavItems:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)checkShowFavIntro:(id)arg1;
- (id)init;
- (void)initMMFavAddTipViewWithTagBtn;
@property(retain, nonatomic) MMToastViewController *m_toastView; // @synthesize m_toastView;
- (void)onClickTipsBtn:(unsigned long long)arg1;
- (void)realAddFavItem:(id)arg1;
@property(nonatomic) _Bool shouldRestoreMainwindow; // @synthesize shouldRestoreMainwindow=_shouldRestoreMainwindow;
- (void)showEnd;
- (void)showSaveResultTip:(id)arg1 andText:(id)arg2;
- (void)webReport:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

