//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMMoviePlayerController.h"

#import "FavForwardLogicDelegate-Protocol.h"
#import "FavTagViewDelegate-Protocol.h"
#import "MMWebViewDelegate-Protocol.h"

@class FavDataItemWrap, FavForwardLogicController, FavoritesItem, FavoritesItemDataField, NSString;

@interface FavMoviePlayerController : MMMoviePlayerController <MMWebViewDelegate, FavTagViewDelegate, FavForwardLogicDelegate>
{
    FavoritesItem *m_favItem;
    FavDataItemWrap *m_favDataWrap;
    FavoritesItemDataField *m_favData;
    FavForwardLogicController *m_favForwardController;
    _Bool m_isActionSheetShowing;
}

- (void).cxx_destruct;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)didReceiveMemoryWarning;
- (id)getFavForawrdViewController;
- (void)handleLongPressEx:(id)arg1;
- (id)initWithFavDataWrap:(id)arg1;
- (id)initWithFavItem:(id)arg1;
@property(retain, nonatomic) FavoritesItemDataField *m_favData; // @synthesize m_favData;
@property(retain, nonatomic) FavDataItemWrap *m_favDataWrap; // @synthesize m_favDataWrap;
@property(retain, nonatomic) FavoritesItem *m_favItem; // @synthesize m_favItem;
- (void)onFavDelete;
- (void)onFavTagEdit;
- (void)onFavTagEditCancel;
- (void)onFavTagEditOK;
- (void)onOperate:(id)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

