//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface FavoritesNoteUtil : NSObject
{
}

+ (id)ConvertFavItem:(id)arg1 toNote:(id)arg2 msg:(id)arg3;
+ (id)ConvertNote2FavItem:(id)arg1 withTitle:(id)arg2 itemList:(id)arg3 originItem:(id)arg4;
+ (id)ConvertWNArticle2FavItem:(id)arg1 withTitle:(id)arg2 dataList:(id)arg3 originItem:(id)arg4;
+ (id)backupNote:(id)arg1 withTitle:(id)arg2 itemList:(id)arg3 originItem:(id)arg4;
+ (id)backupWNArticle:(id)arg1 withTitle:(id)arg2 dataList:(id)arg3 originItem:(id)arg4;
+ (_Bool)checkConflict:(id)arg1 version:(int)arg2 device:(id)arg3;
+ (id)saveOrUpdateNote:(id)arg1 withTitle:(id)arg2 itemList:(id)arg3 tagList:(id)arg4 originItem:(id)arg5;
+ (id)saveOrUpdateWNArticle:(id)arg1 withTitle:(id)arg2 dataList:(id)arg3 originItem:(id)arg4;

@end

