//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface FavTypeObjectItem : NSObject
{
    NSString *_labelText;
    NSString *_imgName;
    NSString *_imgHLName;
    int _type;
}

+ (id)getTextFromType:(int)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *imgHLName; // @synthesize imgHLName=_imgHLName;
@property(retain, nonatomic) NSString *imgName; // @synthesize imgName=_imgName;
- (id)initWithImgName:(id)arg1 hightLightName:(id)arg2 type:(int)arg3 labelText:(id)arg4;
@property(retain, nonatomic) NSString *labelText; // @synthesize labelText=_labelText;
@property(nonatomic) int type; // @synthesize type=_type;

@end

