//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMTableViewCell.h"

@class MMWebImageView, NSString;

@interface GameCenterImageInfoCell : MMTableViewCell
{
    MMWebImageView *_imageView;
    NSString *_imageUrl;
}

- (void).cxx_destruct;
- (void)dealloc;
@property(retain, nonatomic) NSString *imageUrl; // @synthesize imageUrl=_imageUrl;
- (void)initSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)layoutSubviews;
- (void)reloadData;

@end

