//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPUImageFilterGroup.h"

@class GPUImageBilateralFilterCustom, GPUImageBrightnessRefineFilter, GPUImageRawDataInput;

@interface GPUImageLightBoostFilter : GPUImageFilterGroup
{
    GPUImageBrightnessRefineFilter *brightnessRefineFilter;
    GPUImageBilateralFilterCustom *bilateralFilter;
    GPUImageRawDataInput *rawDataCurveInputFilter;
    unsigned int image_width;
    unsigned int image_height;
    unsigned char _meanGray;
    unsigned char _meanGrayTH;
    _Bool _grayLowFlag;
    unsigned char _lowLightCountTH;
    unsigned long long _lightBoostEnable;
    unsigned long long _deNoiseEnable;
    double _maxRatioTH;
    double _maxOffsetTH;
    CDUnknownBlockType _frameBrightnessDidChangeBlock;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned long long deNoiseEnable; // @synthesize deNoiseEnable=_deNoiseEnable;
@property(copy, nonatomic) CDUnknownBlockType frameBrightnessDidChangeBlock; // @synthesize frameBrightnessDidChangeBlock=_frameBrightnessDidChangeBlock;
@property(nonatomic) _Bool grayLowFlag; // @synthesize grayLowFlag=_grayLowFlag;
- (id)init;
@property(nonatomic) unsigned long long lightBoostEnable; // @synthesize lightBoostEnable=_lightBoostEnable;
@property(nonatomic) unsigned char lowLightCountTH; // @synthesize lowLightCountTH=_lowLightCountTH;
@property(nonatomic) double maxOffsetTH; // @synthesize maxOffsetTH=_maxOffsetTH;
@property(nonatomic) double maxRatioTH; // @synthesize maxRatioTH=_maxRatioTH;
@property(nonatomic) unsigned char meanGray; // @synthesize meanGray=_meanGray;
@property(nonatomic) unsigned char meanGrayTH; // @synthesize meanGrayTH=_meanGrayTH;
- (void)notifyMoonStyle:(_Bool)arg1;
- (void)reset;
- (void)updateCurveIndex;

@end

