//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class UIImage;

@interface imgDrawUnit : NSObject
{
    UIImage *_image;
    struct CGRect _bound;
}

- (void).cxx_destruct;
@property(nonatomic) struct CGRect bound; // @synthesize bound=_bound;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;

@end

