//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class CADisplayLink, NSMutableArray;
@protocol ImplicitAnimationControllerDelegate;

@interface ImplicitAnimationObj : NSObject
{
    CADisplayLink *m_displayLink;
    NSMutableArray *m_implicitViews;
    unsigned long long m_countOfViewStartAnimation;
    double m_nextTimeToLetNextViewStartAnimation;
    _Bool _isFromBottom;
    id <ImplicitAnimationControllerDelegate> _delegate;
    CDUnknownBlockType _durationBlock;
}

- (void).cxx_destruct;
- (void)dealloc;
@property(nonatomic) __weak id <ImplicitAnimationControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) CDUnknownBlockType durationBlock; // @synthesize durationBlock=_durationBlock;
@property(nonatomic) _Bool isFromBottom; // @synthesize isFromBottom=_isFromBottom;
- (void)startAnimationWithViews:(id)arg1;
- (void)stopAnimation;
- (void)updateCountOfViewStartAnimationWithCurTime:(double)arg1;
- (void)updateFrame;

@end

