//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "MemberDataLogicProtocol-Protocol.h"

@class NSMutableArray, NSMutableDictionary, NSString;

@interface MemberDataLogic : NSObject <MemberDataLogicProtocol>
{
    NSString *m_adminName;
    NSMutableDictionary *m_dicAllContacts;
    NSMutableArray *m_searchFilterContacts;
    NSMutableArray *m_keyArr;
    NSMutableArray *m_allContacts;
}

- (void).cxx_destruct;
- (void)addContact:(id)arg1;
- (id)addSectionKey:(id)arg1;
- (void)cancelSearch;
- (void)dealloc;
- (void)doSearch:(id)arg1;
- (id)filtContactsByName:(id)arg1;
- (id)getAllContacts;
- (id)getFilteredContacts;
- (id)getItemInSection:(unsigned long long)arg1 atRow:(unsigned long long)arg2;
- (id)getKeyArray;
- (id)getKeyAtSection:(unsigned long long)arg1;
- (unsigned long long)getSectionCount;
- (unsigned long long)getSectionItemCount:(unsigned long long)arg1;
- (unsigned long long)getTotalCount;
- (id)initWithMemberList:(id)arg1 admin:(id)arg2;
- (void)reloadMemberList:(id)arg1;
- (_Bool)removeContact:(id)arg1;
- (void)sortKeys;

@end

