//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSString;
@protocol OS_dispatch_queue;

@interface MessagePatternWrap : NSObject
{
    NSMutableArray *m_arrPatternList;
    _Bool m_bChange;
    NSString *m_nsChatName;
    NSObject<OS_dispatch_queue> *m_worker;
}

+ (id)GetPathOfPatternCacheWithPb:(id)arg1;
- (void).cxx_destruct;
- (void)DelMsg:(id)arg1;
- (void)DelMsgPatten:(id)arg1;
- (id)GetPattern:(id)arg1;
- (void)LoadFromFile;
- (void)RemoveFromFile;
- (void)SaveToFile;
- (void)SetPattern:(id)arg1;
- (void)dealloc;
- (void)doSaveToFile:(id)arg1;
- (id)initWithChatName:(id)arg1 andWorker:(id)arg2;
- (_Bool)isBrandContactMsg:(id)arg1;
@property(retain, nonatomic) NSMutableArray *m_arrPatternList; // @synthesize m_arrPatternList;
@property _Bool m_bChange; // @synthesize m_bChange;
@property(retain, nonatomic) NSString *m_nsChatName; // @synthesize m_nsChatName;

@end

