//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface MMAlbumDataProviderForPHAssetFramework : NSObject
{
}

+ (void)AllMMAlbumsForPHFrameworkWith:(CDUnknownBlockType)arg1 errorBlock:(CDUnknownBlockType)arg2 shouldIncludeVideo:(_Bool)arg3 isOnlyShowVideo:(_Bool)arg4;
+ (id)firstAlbumWithShouldIncludeVideo:(_Bool)arg1 isOnlyShowVideo:(_Bool)arg2;
+ (id)getAlbumFromAlbumType:(long long)arg1 ForSubType:(long long)arg2 shouldIncludeVideo:(_Bool)arg3 isOnlyShowVideo:(_Bool)arg4;
+ (id)getAlbumIdentifier:(id)arg1 shouldIncludeVideo:(_Bool)arg2 isOnlyShowVideo:(_Bool)arg3;
+ (id)getAlbumIdentifiers:(id)arg1 shouldIncludeVideo:(_Bool)arg2 isOnlyShowVideo:(_Bool)arg3;
+ (id)getAlbumSortEndDateFromAlbumType:(long long)arg1 ForSubType:(long long)arg2 shouldIncludeVideo:(_Bool)arg3 isOnlyShowVideo:(_Bool)arg4;

@end

