//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, NSString;

@interface MMCrashReportWrap : NSObject
{
    NSString *m_nsCrashUsrName;
    unsigned int m_uiCrashVersion;
    NSData *m_dtCrashData;
    unsigned long long m_eStackReportType;
    unsigned long long _crashReportSource;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned long long crashReportSource; // @synthesize crashReportSource=_crashReportSource;
- (void)dealloc;
- (id)init;
@property(retain, nonatomic) NSData *m_dtCrashData; // @synthesize m_dtCrashData;
@property(nonatomic) unsigned long long m_eStackReportType; // @synthesize m_eStackReportType;
@property(retain, nonatomic) NSString *m_nsCrashUsrName; // @synthesize m_nsCrashUsrName;
@property(nonatomic) unsigned int m_uiCrashVersion; // @synthesize m_uiCrashVersion;

@end

