//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface MMFavComponentFactory : NSObject
{
}

+ (void)configComData:(id)arg1 withFavItem:(id)arg2;
+ (void)configNoteComData:(id)arg1 withFavItem:(id)arg2;
+ (void)configRecordComData:(id)arg1 withFavItem:(id)arg2;
+ (id)convertVoiceDurationToStr:(unsigned int)arg1;
+ (id)createComponentByFavItem:(id)arg1;
+ (id)createComponentByFavItem:(id)arg1 showDataSize:(_Bool)arg2;
+ (id)createComponentByFavItem:(id)arg1 showDataSize:(_Bool)arg2 hideLine:(_Bool)arg3;
+ (id)createComponentByItemDataField:(id)arg1 inItem:(id)arg2;
+ (int)dataEnumToItemEnum:(int)arg1;
+ (id)getDataThumbPath:(id)arg1 largeImage:(_Bool)arg2;
+ (id)getDomain:(id)arg1;
+ (void)getFavNoteCellTitleAndDesc:(id)arg1 outTitle:(id *)arg2 outDesc:(id *)arg3;
+ (id)getFavTextCellText:(id)arg1;
+ (id)getRecordUrlDataForItem:(id)arg1 hasThumb:(_Bool)arg2;
+ (id)getUrlFrom:(id)arg1;
+ (double)heightForFavItem:(id)arg1 andIsEdit:(_Bool)arg2;
+ (double)heightForItemDataField:(id)arg1 inItem:(id)arg2;

@end

