//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class BBHostInfo, NSArray, NSData, NSDate;

@interface MMHostResolutionOperation : NSObject
{
    struct __CFHost *_cfHostName;
    _Bool _isResolved;
    BBHostInfo *_hostInformation;
    NSData *_sockaddrBytes;
    NSArray *_ipStrings;
    NSArray *_hostNames;
    CDUnknownBlockType _callback;
    NSDate *_startDate;
    NSDate *_endDate;
}

- (void).cxx_destruct;
- (void)_cleanUp;
- (void)_compileResultsFromCallbacks;
- (void)_failedResolvingHostWithStreamError:(CDStruct_87dc826d)arg1;
- (_Bool)_startResolving;
@property(copy, nonatomic) CDUnknownBlockType callback; // @synthesize callback=_callback;
- (void)completeOperationForType:(int)arg1;
- (void)dealloc;
@property(retain, nonatomic) NSDate *endDate; // @synthesize endDate=_endDate;
- (id)extractHostAddresses:(id)arg1;
- (id)extractHostNames:(id)arg1;
@property(readonly, nonatomic) BBHostInfo *hostInformation; // @synthesize hostInformation=_hostInformation;
@property(readonly, nonatomic) NSArray *hostNames; // @synthesize hostNames=_hostNames;
- (id)init;
- (id)initWithHostName:(id)arg1;
@property(readonly, nonatomic) NSArray *ipStrings; // @synthesize ipStrings=_ipStrings;
@property(readonly, nonatomic) _Bool isResolved; // @synthesize isResolved=_isResolved;
@property(retain, nonatomic) NSDate *startDate; // @synthesize startDate=_startDate;
@property(readonly, nonatomic) NSData *sockaddrBytes; // @synthesize sockaddrBytes=_sockaddrBytes;
- (void)startWithCallback:(CDUnknownBlockType)arg1;

@end

