//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MMImagePickerReportInfo, NSArray, NSDictionary, NSString, SightDraft;

@protocol MMImagePickerControlCenter <NSObject>
@property(nonatomic) _Bool canHybridSendAsset;
@property(nonatomic) _Bool canSendGif;
@property(nonatomic) _Bool canSendMultiImage;
@property(nonatomic) _Bool canSendOriginImage;
@property(nonatomic) _Bool canSendVideoMessage;
- (void)cancelImagePicker;
@property(nonatomic) int compressType;
@property(retain, nonatomic) NSString *currentAlbum;
@property(retain, nonatomic) NSString *finishWording;
@property(nonatomic) _Bool isEditMode;
@property(nonatomic) _Bool isNotShowVideoSizeAlertView;
@property(nonatomic) _Bool isOnlyShowVideoMessage;
@property(nonatomic) _Bool isOriginalImage;
@property(nonatomic) int maxImageCount;
@property(nonatomic) _Bool needThumbImage;
- (void)selectedAssets:(NSArray *)arg1;
@property(retain, nonatomic) NSArray *selectedImageAssets;
@property(retain, nonatomic) NSArray *selectedImageURLs;
- (void)selectedSight:(SightDraft *)arg1;
- (void)selectedVideo:(NSDictionary *)arg1;
@property(nonatomic) _Bool showPreviewView;

@optional
- (int)getPickerScene;
- (void)increasePreviewCount;
- (MMImagePickerReportInfo *)pickerReportInfo;
- (void)reportPicerReportInfo;
- (void)reportPreviewCount;
@end

