//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MMCommon/MMService.h>

#import "IClearDataMgrExt-Protocol.h"
#import "MMService-Protocol.h"

@class NSBundle, NSString;

@interface MMLanguageMgr : MMService <IClearDataMgrExt, MMService>
{
    NSString *m_nsCurSystemLanguage;
    NSString *m_curLanguage;
    NSBundle *m_curBundle;
    NSBundle *m_backupBundle;
    _Bool bDownloadPackageRightNow;
}

- (void).cxx_destruct;
- (void)ClearOlderVersionData;
- (_Bool)curLanguageIsChineseTraditional;
- (void)dealloc;
- (id)getBackUpLanguage;
- (id)getCurBundle;
- (id)getCurLanguage;
- (id)getCurLanguageDisplayName;
- (id)getCurSystemLanguage;
- (id)getLangPackageFileForLang:(id)arg1;
- (id)getLangPackageNotVerifiedFileForLang:(id)arg1;
- (id)getLangPackagePathForLang:(id)arg1;
- (id)getLangPackageRootPath;
- (id)getLangPackageVerifiedFailFileForLang:(id)arg1;
- (id)getLangPackageZipFileForLang:(id)arg1;
- (id)getLanguagePath;
- (id)getRealCurSystemLanguage;
- (id)getStringForCurLanguage:(id)arg1 defaultString:(id)arg2;
- (id)getStringForCurLanguage:(id)arg1 defaultTo:(id)arg2;
- (id)getStringForCurLanguage:(id)arg1 defaultTo:(id)arg2 table:(id)arg3;
- (id)getStringForCurLanguageWithBackupBundle:(id)arg1 defaultTo:(id)arg2;
- (id)getStringForCurLanguageWithBackupBundle:(id)arg1 defaultTo:(id)arg2 table:(id)arg3;
- (id)getStringForCurSystemLanguage:(id)arg1 defaultTo:(id)arg2;
- (id)getStringForLanguage:(id)arg1 withID:(id)arg2 defaultTo:(id)arg3;
- (id)getSupportedLanguageDisplayNames;
- (id)getSupportedLanguages;
- (_Bool)ifNeedBackupBundle;
- (id)init;
- (void)initBackUpLanguage;
- (void)initLanguage;
- (id)internalGetCurLanguage;
- (void)internalSetCurLanguage:(id)arg1;
- (_Bool)isLanaguageValid;
- (id)isSupportedLanguage:(id)arg1;
- (_Bool)isVersionString:(id)arg1 olderThanMajor:(unsigned int *)arg2 minor:(unsigned int *)arg3 minorex:(unsigned int *)arg4;
- (void)onDiskStorageWarningCleanedSize:(unsigned long long *)arg1;
- (void)onDiskStorageWarningCleanedSize:(unsigned long long *)arg1 CacheMask:(unsigned int)arg2;
- (void)onDiskStorageWarningCleanedSize:(unsigned long long *)arg1 subQueue:(id)arg2;
- (void)refreshNewVersionForCurLanguage:(id)arg1 fromViewScene:(unsigned int)arg2;
- (void)setCurLanguage:(id)arg1 forRefresh:(_Bool)arg2 withViewScene:(unsigned int)arg3 shouldChangeMainFrame:(_Bool)arg4;
- (void)setCurLanguage:(id)arg1 shouldChangeMainFrame:(_Bool)arg2;
- (id)trimForiOS9Plus:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

