//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MMCommon/MMObject.h>

#import "WCTTableCoding-Protocol.h"

@class NSString;

@interface MMResConfigInfo : MMObject <WCTTableCoding>
{
    unsigned int _configCrc32;
    NSString *_configId;
    NSString *_configResoureces;
    NSString *_configUrl;
}

+ (const list_2812bee2 *)AllProperties;
+ (const struct WCTAnyProperty *)AnyProperty;
+ (const struct WCTProperty *)configCrc32;
+ (const struct WCTProperty *)configId;
+ (const struct WCTProperty *)configResoureces;
+ (const struct WCTProperty *)configUrl;
+ (const struct WCTBinding *)objectRelationalMappingForWCDB;
- (void).cxx_destruct;
@property(nonatomic) unsigned int configCrc32; // @synthesize configCrc32=_configCrc32;
@property(retain, nonatomic) NSString *configId; // @synthesize configId=_configId;
@property(retain, nonatomic) NSString *configResoureces; // @synthesize configResoureces=_configResoureces;
@property(retain, nonatomic) NSString *configUrl; // @synthesize configUrl=_configUrl;

// Remaining properties
@property(nonatomic) _Bool isAutoIncrement;
@property(nonatomic) long long lastInsertedRowID;

@end

