//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSSet, UIEvent;

@protocol MMTransparentButtonDelegate <NSObject>

@optional
- (void)MMTransparentButton_touchesBegan:(NSSet *)arg1 withEvent:(UIEvent *)arg2;
- (void)MMTransparentButton_touchesCancelled:(NSSet *)arg1 withEvent:(UIEvent *)arg2;
- (void)MMTransparentButton_touchesEnded:(NSSet *)arg1 withEvent:(UIEvent *)arg2;
- (void)MMTransparentButton_touchesMoved:(NSSet *)arg1 withEvent:(UIEvent *)arg2;
@end

