//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMSearchBar.h"

#import "IRecordPermissionCheckExt-Protocol.h"
#import "IVOIPUILogicMgrExt-Protocol.h"
#import "IVoiceSearchExt-Protocol.h"
#import "SearchGuideViewDelegate-Protocol.h"
#import "UIAlertViewDelegate-Protocol.h"
#import "VoiceSearchContactsViewDelegate-Protocol.h"

@class NSString, SearchGuideView, UIButton, UIView, UIViewController, VoiceRecogView;
@protocol MMVoiceSearchBarDelegate, MMVoiceSearchDelegate;

@interface MMVoiceSearchBar : MMSearchBar <IVOIPUILogicMgrExt, UIAlertViewDelegate, IVoiceSearchExt, IRecordPermissionCheckExt, VoiceSearchContactsViewDelegate, SearchGuideViewDelegate>
{
    UIButton *m_voiceSearchBackButton;
    UIButton *m_searchingCancelButton;
    UIViewController *m_parentViewController;
    UIView *m_preventSearchBarView;
    UIButton *m_voiceSearchBtn;
    int m_voiceSearchStatus;
    int m_voiceSearchSpecies;
    _Bool m_useDefaultDisplayController;
    _Bool m_indexBarEffect;
    VoiceRecogView *m_voiceRecogView;
    id <MMVoiceSearchDelegate> m_voiceSearchDelegate;
    id <MMVoiceSearchBarDelegate> m_voiceSearchBarDelegate;
    unsigned int m_voiceID;
    _Bool m_bVoiceSearchEnabled;
    _Bool m_bRealTimeSearch;
    double m_fCancelButtonWidth;
    _Bool m_showBlurEffectView;
    SEL mRecordSelector;
    SearchGuideView *_ftsGuideView;
}

- (void).cxx_destruct;
- (void)OnEndRecord;
- (void)OnError:(int)arg1 andSearchId:(unsigned int)arg2;
- (void)OnGetSearchResult:(id)arg1 andSearchId:(unsigned int)arg2;
- (void)OnLevelMeter:(unsigned int)arg1 Peak:(float)arg2;
- (void)OnRecordDenied;
- (void)OnRecordPermissioned;
- (void)OnStartRecord;
- (void)SetVoiceSearchBackBtnOnTheView:(_Bool)arg1;
- (void)SimulateSearchBackBtnClick;
- (void)adjustDimmingViewRect;
- (void)backButtonDone:(id)arg1;
- (void)callVoiceSearchMgrStart;
- (_Bool)callVoiceSearchMgrStop;
- (_Bool)canFromStatus:(int)arg1 transferToStatus:(int)arg2;
- (void)dealloc;
- (id)filterContactsViewContacts:(id)arg1;
- (void)finishSearch;
@property(retain, nonatomic, getter=getSearchGuideView) SearchGuideView *ftsGuideView; // @synthesize ftsGuideView=_ftsGuideView;
- (unsigned int)getVoiceID;
- (void)handleRotateEvent;
- (_Bool)handleVoiceSearchResults:(id)arg1;
- (void)hiddenBlurEffectView;
- (void)hideVoiceSearch;
- (id)initWithContentsController:(id)arg1 withParentViewController:(id)arg2 withSpecies:(int)arg3 withUseDefaultDisplayController:(_Bool)arg4;
- (id)initWithContentsController:(id)arg1 withParentViewController:(id)arg2 withSpecies:(int)arg3 withUseDefaultDisplayController:(_Bool)arg4 hasIndexBar:(_Bool)arg5;
- (_Bool)isVoiceSearchActive;
- (void)loadView;
@property(nonatomic) SEL mRecordSelector; // @synthesize mRecordSelector;
@property(nonatomic) _Bool m_bRealTimeSearch; // @synthesize m_bRealTimeSearch;
@property(nonatomic) _Bool m_showBlurEffectView; // @synthesize m_showBlurEffectView;
@property(nonatomic) __weak id <MMVoiceSearchBarDelegate> m_voiceSearchBarDelegate; // @synthesize m_voiceSearchBarDelegate;
@property(nonatomic) __weak id <MMVoiceSearchDelegate> m_voiceSearchDelegate; // @synthesize m_voiceSearchDelegate;
- (void)onVideoVoipViewDidAppear:(id)arg1;
- (void)onVideoVoipViewDisappear;
- (void)openContactInfoView:(int)arg1;
- (void)resetVoiceSearchBarFrame;
- (_Bool)searchBar:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)searchBarCancelButtonClicked:(id)arg1;
- (void)searchBarSearchButtonClicked:(id)arg1;
- (_Bool)searchBarShouldBeginEditing:(id)arg1;
- (_Bool)searchBarShouldEndEditing:(id)arg1;
- (void)searchBarTextDidBeginEditing:(id)arg1;
- (void)searchBarTextDidEndEditing:(id)arg1;
- (void)searchDisplayController:(id)arg1 willHideSearchResultsTableView:(id)arg2;
- (void)searchDisplayControllerWillEndSearch:(id)arg1;
- (void)setVoiceSearchBarFrame:(_Bool)arg1 animation:(_Bool)arg2;
- (_Bool)setVoiceSearchStatusFrom:(int)arg1 transferToStatus:(int)arg2;
- (_Bool)setVoiceSearchStatusFrom:(int)arg1 transferToStatus:(int)arg2 withVoiceID:(int)arg3;
- (void)setVoiceSearchToParentView:(id)arg1;
- (void)showContactInfoView:(id)arg1;
- (void)showVoiceSearchButton:(_Bool)arg1;
- (void)startSearchTableViewCancelingAnimation;
- (void)startVoiceSearch;
- (void)statusFrameChange:(id)arg1;
- (_Bool)stopVoiceSearch;
- (void)tryShowBlurEffectView;
- (id)usrNameConvertToOContacts:(id)arg1;
- (void)voiceSearchBackToPreviousView;
- (void)voiceSearchBtnRealDone;
- (void)voiceSearchButtonClick;
- (void)voiceSearchButtonDone;
- (void)voiceSearchByMainFrameRealDone;
- (void)voiceSearchCancelButtonDone;
- (void)voiceSearchContactsViewBack;
- (void)voiceSearchContactsViewCancel;
- (void)voiceSearchRecordDone;
- (void)voiceSearchRestart;
- (id)voiceSearchResultsTableView:(id)arg1 andCell:(id)arg2 cellForRowAtIndexPath:(id)arg3;
- (void)voiceSearchResultsTableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)voiceSearchResultsTableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)voiceSearchResultsTableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)voiceSearchStartByNewMainFrame;
- (void)voiceSearchViewErrorCancelButtonDone;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

