//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "UIWebViewDelegate-Protocol.h"

@class NSString, UIWebView;

@interface MMWCWebviewCacheCleaner : NSObject <UIWebViewDelegate>
{
    _Bool _bHaveReload;
    UIWebView *_unvisiableWebView;
}

- (void).cxx_destruct;
- (void)cleanCacheForMainUrl:(id)arg1;
@property(retain, nonatomic) UIWebView *unvisiableWebView; // @synthesize unvisiableWebView=_unvisiableWebView;
- (void)webViewDidFinishLoad:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

