//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMWebViewPluginBase.h"

#import "IMMWebViewReportStatMgrExt-Protocol.h"

@class NSString;

@interface MMWebViewPlugin_ReportPageEvent : MMWebViewPluginBase <IMMWebViewReportStatMgrExt>
{
    NSString *_nsSessionID;
    NSString *_referLoadUrl;
    NSString *_currentLoadUrl;
    unsigned long long _enterPageTime;
    unsigned long long _costLoadTime;
    long long _scene;
    unsigned long long _recentMenuType;
}

+ (unsigned long long)getCurrentTimeInMs;
+ (unsigned int)getCurrentTimeStamp;
+ (unsigned long long)getNetType;
+ (id)getUserAgent;
+ (void)reportPageInfoWhenForwardMsgOrFav:(id)arg1 actionType:(unsigned long long)arg2 fromScene:(unsigned long long)arg3 ret:(unsigned long long)arg4;
- (void).cxx_destruct;
- (void)dealloc;
- (void)genSessionID;
- (id)getAppID;
- (id)getCurrentUrl;
- (id)getSessionID;
- (_Bool)handleEvent:(unsigned long long)arg1 userInfo:(id)arg2;
- (id)init;
- (void)onMenuActionRet:(unsigned long long)arg1;
- (void)realReportMenuActionWithType:(unsigned long long)arg1 result:(unsigned long long)arg2;
- (_Bool)reportPageEventFrom3rdProvideInfoWithKey:(id)arg1 andValue:(id)arg2;
- (void)reportPageEventWhenClickMenuAction:(unsigned long long)arg1;
- (void)reportPageEventWhenPageLeft:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

