//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSData.h>

@interface NSData (WXCBase64Addtion)
+ (id)decodeBase64ForString:(id)arg1;
+ (id)decodeWebSafeBase64ForString:(id)arg1;
- (id)encodeBase64ForData;
- (id)encodeWebSafeBase64ForData;
@end

