//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSArray;

@interface QBIPInfo : NSObject <NSCoding>
{
    int _eIPType;
    int _iTotalPollNum;
    int _currPollNum;
    int _currIpIndex;
    double _lifeTimeSince1970;
    NSArray *_ipArrays;
}

- (void).cxx_destruct;
@property(nonatomic) int currIpIndex; // @synthesize currIpIndex=_currIpIndex;
@property(nonatomic) int currPollNum; // @synthesize currPollNum=_currPollNum;
@property(nonatomic) int eIPType; // @synthesize eIPType=_eIPType;
- (void)encodeWithCoder:(id)arg1;
@property(nonatomic) int iTotalPollNum; // @synthesize iTotalPollNum=_iTotalPollNum;
- (id)init;
- (id)initWithCoder:(id)arg1;
@property(retain, nonatomic) NSArray *ipArrays; // @synthesize ipArrays=_ipArrays;
@property(nonatomic) double lifeTimeSince1970; // @synthesize lifeTimeSince1970=_lifeTimeSince1970;

@end

