//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, QDBDatabase, QDataStoreSelectorTencent, QDataStoreSelectorWorldmap;

@interface QDataCacheSql : NSObject
{
    QDataStoreSelectorTencent *_tencent;
    QDataStoreSelectorWorldmap *_worldmap;
    NSString *_dbpath;
    QDBDatabase *_db;
}

+ (id)singlton;
- (void).cxx_destruct;
- (void)close;
@property(retain, nonatomic) QDBDatabase *db; // @synthesize db=_db;
@property(retain, nonatomic) NSString *dbpath; // @synthesize dbpath=_dbpath;
- (void)dealloc;
- (id)decryptItem:(id)arg1;
- (id)encryptItem:(id)arg1;
- (_Bool)executeInsert:(id)arg1;
- (_Bool)executeQuery:(id)arg1;
- (_Bool)executeUpdate:(id)arg1;
- (void)initData;
- (id)initWithPath:(id)arg1;
- (void)open;
- (void)resetDataWith:(id)arg1;
- (id)selector:(id)arg1;
@property(retain, nonatomic) QDataStoreSelectorTencent *tencent; // @synthesize tencent=_tencent;
@property(retain, nonatomic) QDataStoreSelectorWorldmap *worldmap; // @synthesize worldmap=_worldmap;

@end

