//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MMCommon/MMObject.h>

#import "ICdnComMgrExt-Protocol.h"
#import "PBMessageObserverDelegate-Protocol.h"
#import "RecordUploadTaskDelegate-Protocol.h"

@class CMessageWrap, NSMutableArray, NSString, RecordUploadTask;
@protocol RecordUploadCDNMgrDelegate;

@interface RecordUploadCDNMgr : MMObject <RecordUploadTaskDelegate, ICdnComMgrExt, PBMessageObserverDelegate>
{
    NSMutableArray *m_arrMsgWrap;
    NSMutableArray *m_arrRecordData;
    NSMutableArray *m_arrCDNUploadInfo;
    CMessageWrap *m_curMsgWrap;
    RecordUploadTask *m_curUploadTask;
    id <RecordUploadCDNMgrDelegate> m_delegate;
}

- (void).cxx_destruct;
- (void)AddUploadTaskForDataList:(id)arg1 isFromRecord:(_Bool)arg2;
- (void)BatchTransCDNItemForFav;
- (void)BatchTransCDNItemForMsg:(_Bool)arg1;
- (void)CheckCDNUploadMsgQueue;
- (void)HandleBatchTransCDNResp:(id)arg1;
- (void)HandleSendMsgResp:(id)arg1;
- (_Bool)IsRecordMsgUploading:(id)arg1;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (void)OnRecordUploadTaskFail;
- (void)OnRecordUploadTaskFinish:(id)arg1;
- (void)OnSetCdnDnsInfo;
- (void)RemoveMsgWrap:(id)arg1;
- (_Bool)SendCurAppMsg;
- (void)SendMsgFail;
- (void)SendMsgOK:(long long)arg1;
- (void)StartUploadRecordMsg:(id)arg1;
- (void)StopCurUpload;
- (void)StopUploadRecordMsg:(id)arg1;
- (void)StopUploadRecordMsgByUsername:(id)arg1;
- (void)TryNextMsgWrap;
- (void)UploadRecordData;
- (void)dealloc;
- (id)findRecordDataInList:(id)arg1 WithLocalDataId:(id)arg2;
- (id)init;
@property(retain, nonatomic) CMessageWrap *m_curMsgWrap; // @synthesize m_curMsgWrap;
@property(nonatomic) __weak id <RecordUploadCDNMgrDelegate> m_delegate; // @synthesize m_delegate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

