//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "UIAlertViewDelegate-Protocol.h"

@class NSString, UIButton;

@interface RecoverDeviceDBViewController : MMUIViewController <UIAlertViewDelegate>
{
    UIButton *_btnRecover;
}

- (void).cxx_destruct;
- (void)DoRecover;
- (void)OnRecover;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)initView;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

