//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MMCommon/WXPBGeneratedMessage.h>

@class StatisticsAppInfo, StatisticsBrandVideoAdInfo, StatisticsSnsAdInfo;

@interface StatisticsExtInfo : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) StatisticsBrandVideoAdInfo *brandVideoAdInfo; // @dynamic brandVideoAdInfo;
@property(retain, nonatomic) StatisticsSnsAdInfo *snsAdInfo; // @dynamic snsAdInfo;
@property(retain, nonatomic) StatisticsAppInfo *sourceAppInfo; // @dynamic sourceAppInfo;

@end

