//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSSet, UIEvent;

@protocol tableViewDelegate <NSObject>

@optional
- (void)didFinishedLoading:(id)arg1;
- (void)touchesBegan_TableView:(NSSet *)arg1 withEvent:(UIEvent *)arg2;
- (void)touchesCancelled_TableView:(NSSet *)arg1 withEvent:(UIEvent *)arg2;
- (void)touchesEnded_TableView:(NSSet *)arg1 withEvent:(UIEvent *)arg2;
- (void)touchesMoved_TableView:(NSSet *)arg1 withEvent:(UIEvent *)arg2;
@end

