//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MMCommon/MMObject.h>

#import "PBCoding-Protocol.h"

@class NSString;

@interface TranslateInfo : MMObject <PBCoding>
{
    unsigned int mesLocalId;
    NSString *originText;
    NSString *originLang;
    NSString *translatedText;
    NSString *translatedLang;
    _Bool showOriginTextNow;
    int translateStatus;
    NSString *brandWording;
    NSString *snsID;
    _Bool bNeedShowAnimation;
    NSString *displayTranslatedText;
}

+ (void)initialize;
- (void).cxx_destruct;
- (int)GetTranslateStatus;
@property(nonatomic) _Bool bNeedShowAnimation; // @synthesize bNeedShowAnimation;
@property(retain, nonatomic) NSString *brandWording; // @synthesize brandWording;
@property(retain, nonatomic) NSString *displayTranslatedText; // @synthesize displayTranslatedText;
- (id)getDisplayContent;
- (const map_490096f0 *)getValueTagIndexMap;
- (id)getValueTypeTable;
- (id)init;
- (_Bool)isTextTooLong;
- (_Bool)isTranslateFailed;
- (_Bool)isTranslating;
@property(nonatomic) unsigned int mesLocalId; // @synthesize mesLocalId;
@property(retain, nonatomic) NSString *originLang; // @synthesize originLang;
@property(retain, nonatomic) NSString *originText; // @synthesize originText;
@property(nonatomic) _Bool showOriginTextNow; // @synthesize showOriginTextNow;
@property(retain, nonatomic) NSString *snsID; // @synthesize snsID;
@property(nonatomic) int translateStatus; // @synthesize translateStatus;
@property(retain, nonatomic) NSString *translatedLang; // @synthesize translatedLang;
@property(retain, nonatomic) NSString *translatedText; // @synthesize translatedText;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

