//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSIndexPath, UITableView, UITableViewCell;

@protocol VoiceSearchContactsViewDelegate <NSObject>
- (unsigned int)getVoiceID;
- (void)voiceSearchContactsViewBack;
- (void)voiceSearchContactsViewCancel;
- (UITableViewCell *)voiceSearchResultsTableView:(UITableView *)arg1 andCell:(UITableViewCell *)arg2 cellForRowAtIndexPath:(NSIndexPath *)arg3;
- (void)voiceSearchResultsTableView:(UITableView *)arg1 didSelectRowAtIndexPath:(NSIndexPath *)arg2;
- (double)voiceSearchResultsTableView:(UITableView *)arg1 heightForRowAtIndexPath:(NSIndexPath *)arg2;
- (long long)voiceSearchResultsTableView:(UITableView *)arg1 numberOfRowsInSection:(long long)arg2;
@end

