//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAAppMessageBaseCellView.h"

#import "IMsgExt-Protocol.h"

@class MMUILabel, MMWebImageView, UIImageView, WAAppPageViewModel, YYAsyncImageView;

@interface WAAppPageCellView : WAAppMessageBaseCellView <IMsgExt>
{
    MMWebImageView *_appLogoView;
    MMUILabel *_appNameLabel;
    UIImageView *_defaultLogo;
    YYAsyncImageView *_imageView;
    MMUILabel *_titleLabel;
}

- (void).cxx_destruct;
- (void)OnMsgDownloadThumbOK:(id)arg1 MsgWrap:(id)arg2;
@property(retain, nonatomic) MMWebImageView *appLogoView; // @synthesize appLogoView=_appLogoView;
@property(retain, nonatomic) MMUILabel *appNameLabel; // @synthesize appNameLabel=_appNameLabel;
- (void)dealloc;
@property(retain, nonatomic) UIImageView *defaultLogo; // @synthesize defaultLogo=_defaultLogo;
- (id)displayViewForImageBrowser;
@property(retain, nonatomic) YYAsyncImageView *imageView; // @synthesize imageView=_imageView;
- (void)initHeaderView;
- (void)initPageImageView;
- (void)initTitleView;
- (id)initWithViewModel:(id)arg1;
- (void)layoutContentView;
- (void)onTouchDown;
- (void)onTouchUpInside;
@property(retain, nonatomic) MMUILabel *titleLabel; // @synthesize titleLabel=_titleLabel;

// Remaining properties
@property(readonly, nonatomic) WAAppPageViewModel *viewModel; // @dynamic viewModel;

@end

