//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAJSContextPluginBase.h"

#import "ILocationMgrExt-Protocol.h"
#import "INetworkStatusMgrExt-Protocol.h"

@class CMMotionManager;
@protocol IJSContextPluginDelegate;

@interface WAJSContextPlugin_coreMotion : WAJSContextPluginBase <ILocationMgrExt, INetworkStatusMgrExt>
{
    CMMotionManager *_motionMgr;
    unsigned long long m_headingTag;
    _Bool _accelerometerWorking;
    _Bool _accelerometerPauseBySuspend;
    _Bool _compassWorking;
    _Bool _compassPauseBySuspend;
    id <IJSContextPluginDelegate> _resultDelegate;
}

- (void).cxx_destruct;
- (void)dealloc;
- (void)enableAccelerometer;
- (void)enableAccelerometer:(_Bool)arg1;
- (void)enableCompass;
- (void)enableCompass:(_Bool)arg1;
- (_Bool)handleEvent:(long long)arg1 userInfo:(id)arg2;
- (id)init;
- (void)onHeadingChanged:(id)arg1 withTag:(unsigned long long)arg2;
- (void)onHeadingError:(int)arg1 withTag:(unsigned long long)arg2;
- (void)onNetworkStatusChange:(unsigned int)arg1;
@property(nonatomic) __weak id <IJSContextPluginDelegate> resultDelegate; // @synthesize resultDelegate=_resultDelegate;
- (void)stopAccelerometerBySuspend:(_Bool)arg1;
- (void)stopCompassBySuspend:(_Bool)arg1;

@end

