//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAJSEventHandler_BaseEvent.h"

#import "MMPickLocationViewControllerDelegate-Protocol.h"

@class MMPickLocationViewController;

@interface WAJSEventHandler_chooseLocation : WAJSEventHandler_BaseEvent <MMPickLocationViewControllerDelegate>
{
    MMPickLocationViewController *m_pickLocationController;
}

- (void).cxx_destruct;
- (void)handleJSEvent:(id)arg1;
- (void)onCancelSeletctedLocation;
- (void)onFinishSelectedLocation;
- (id)onGetRightBarButton;
- (void)openLocation;

@end

