//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "WAJumpBackAnimatedTransitionDelegate-Protocol.h"
#import "WAJumpBackInteractiveTransitionDelegate-Protocol.h"
#import "WAJumpPushAnimatedTransitionDelegate-Protocol.h"

@class CContact, NSString, UIScreenEdgePanGestureRecognizer, WAJumpBackInteractiveTransition, WALoadingViewOpenWeAppInfo;
@protocol WALoadingViewControllerDelegate;

@interface WALoadingViewController : MMUIViewController <WAJumpPushAnimatedTransitionDelegate, WAJumpBackAnimatedTransitionDelegate, WAJumpBackInteractiveTransitionDelegate>
{
    _Bool m_isBlackStatusBar;
    _Bool _isViewDidAppear;
    _Bool _isPopMyselfAfterDidAppear;
    _Bool _isCallPopMySelf;
    _Bool _isLoadingAnimationDone;
    UIScreenEdgePanGestureRecognizer *_jumpBackInteractivePopGesture;
    WAJumpBackInteractiveTransition *_jumpBackInteractiveTransition;
    _Bool _isCallReturn;
    _Bool _isUseJumpWeAppAnimatedTransition;
    _Bool _isDoingJumpWeAppPushAnimation;
    CContact *_contact;
    id <WALoadingViewControllerDelegate> _delegate;
    NSString *_pagePath;
    NSString *_navTitle;
    NSString *_backColorStr;
    CDUnknownBlockType _viewDidAppearCallback;
    WALoadingViewOpenWeAppInfo *_openWeAppInfo;
}

- (void).cxx_destruct;
- (void)addJumpBackInteractivePopGesture;
@property(copy, nonatomic) NSString *backColorStr; // @synthesize backColorStr=_backColorStr;
- (void)callOnLoadingAnimationDoneAfterViewDidAppear;
- (void)changeStatusBarToBlack:(_Bool)arg1;
- (void)checkOpenWeApp;
@property(retain, nonatomic) CContact *contact; // @synthesize contact=_contact;
- (void)dealloc;
@property(nonatomic) __weak id <WALoadingViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (id)initWithContact:(id)arg1 pagePath:(id)arg2;
@property(nonatomic) _Bool isCallReturn; // @synthesize isCallReturn=_isCallReturn;
@property(nonatomic) _Bool isDoingJumpWeAppPushAnimation; // @synthesize isDoingJumpWeAppPushAnimation=_isDoingJumpWeAppPushAnimation;
- (_Bool)isEnableJumpBackInteractivePopGesture;
@property(nonatomic) _Bool isUseJumpWeAppAnimatedTransition; // @synthesize isUseJumpWeAppAnimatedTransition=_isUseJumpWeAppAnimatedTransition;
- (_Bool)isViewDidAppear;
- (id)loadCacheLoadingConfig:(id)arg1;
- (void)markLoadingAnimationDone;
- (id)mmNavigationController:(id)arg1 animationControllerForOperation:(long long)arg2 fromViewController:(id)arg3 toViewController:(id)arg4;
- (id)mmNavigationController:(id)arg1 interactionControllerForAnimationController:(id)arg2;
@property(copy, nonatomic) NSString *navTitle; // @synthesize navTitle=_navTitle;
- (void)onJumpBackAnimationDone:(_Bool)arg1 animatedTransition:(id)arg2;
- (void)onJumpBackInteractiveTransitionBegin:(id)arg1;
- (void)onJumpPushAnimationDone:(_Bool)arg1 animatedTransition:(id)arg2;
- (void)onReturn;
@property(retain, nonatomic) WALoadingViewOpenWeAppInfo *openWeAppInfo; // @synthesize openWeAppInfo=_openWeAppInfo;
@property(copy, nonatomic) NSString *pagePath; // @synthesize pagePath=_pagePath;
- (void)popMyselfAfterViewDidAppear;
- (void)popMyselfViewController;
- (void)removeJumpBackInteractivePopGesture;
- (void)removeMyselfInViewControllers;
- (void)setThumbImage:(id)arg1;
@property(copy, nonatomic) CDUnknownBlockType viewDidAppearCallback; // @synthesize viewDidAppearCallback=_viewDidAppearCallback;
- (void)showDownloadingProgressView;
- (void)startEnterAppAnimation;
- (void)updateLeftBarItemWithNavMode:(int)arg1;
- (_Bool)useBlackStatusbar;
- (_Bool)useTransparentNavibar;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidBePoped:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

