//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "PBMessageObserverDelegate-Protocol.h"
#import "UIAlertViewDelegate-Protocol.h"
#import "WAAppActionSheetDelegate-Protocol.h"
#import "WCActionSheetDelegate-Protocol.h"

@class NSString, WAAppActionSheet;
@protocol WASessionContentLogicHandlerDelegate;

@interface WASessionContentLogicHandler : NSObject <PBMessageObserverDelegate, WCActionSheetDelegate, UIAlertViewDelegate, WAAppActionSheetDelegate>
{
    _Bool _isRequestedEnterSession;
    WAAppActionSheet *_actionSheet;
    id <WASessionContentLogicHandlerDelegate> _delegate;
}

- (void).cxx_destruct;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)confirmBlockMsgActionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)confirmReceiveMsgActionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)dealloc;
@property(nonatomic) __weak id <WASessionContentLogicHandlerDelegate> delegate; // @synthesize delegate=_delegate;
- (unsigned int)getAppVersion;
- (id)getContact;
- (unsigned long long)getDebugMode;
- (unsigned long long)getEnterScene;
- (id)getNavigationController;
- (id)getPageID;
- (id)getSceneID;
- (id)getSessionContentViewController;
- (id)menubuttonTitleArray;
- (void)onClickWeAppReceiveSessionMsg;
- (void)onResponseEnterSession:(id)arg1;
- (void)onRightBtnActionSheetClickBlockSessionMessage;
- (void)onRightBtnActionSheetClickCancel;
- (void)onRightBtnActionSheetClickReceiveSessionMessage;
- (void)onWAActionSheetClickButtonWithButtonTitle:(id)arg1;
- (void)onWAActionSheetInfoClicked;
- (void)openDetail;
- (void)openWeApp;
- (void)openWeAppAboutUs;
- (void)requestEnterSessionCGIWithSessionFrom:(id)arg1;
- (void)showRightBtnActionSheetWithShowHomePage:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

