//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAWebViewPluginBase.h"

#import "IMsgExt-Protocol.h"

@class NSString;

@interface WAWebViewPlugin_KFSession : WAWebViewPluginBase <IMsgExt>
{
    NSString *_userName;
    unsigned int _lastUnreadCount;
}

- (void).cxx_destruct;
- (void)OnAddMsgListForSession:(id)arg1 NotifyUsrName:(id)arg2;
- (void)OnUnReadCountChange:(id)arg1;
- (void)checkUnreadCountChange;
- (void)dealloc;
- (unsigned int)getSessionUnreadCount;
- (id)init;
- (void)notifyUnreadCountChangeTo:(unsigned int)arg1;

@end

