//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MMCommon/MMObject.h>

#import "PBCoding-Protocol.h"

@class NSString;

@interface WCCardEntryTips : MMObject <PBCoding>
{
    _Bool bShowNew;
    _Bool bShowRedDot;
    _Bool bNeedCheck;
    NSString *nsRedDotBuff;
    NSString *nsTipWording;
    NSString *nsTipIconUrl;
    NSString *nsCardId;
}

+ (void)initialize;
- (void).cxx_destruct;
@property(nonatomic) _Bool bNeedCheck; // @synthesize bNeedCheck;
@property(nonatomic) _Bool bShowNew; // @synthesize bShowNew;
@property(nonatomic) _Bool bShowRedDot; // @synthesize bShowRedDot;
- (const map_490096f0 *)getValueTagIndexMap;
- (id)getValueTypeTable;
- (void)loadFromCache;
@property(retain, nonatomic) NSString *nsCardId; // @synthesize nsCardId;
@property(retain, nonatomic) NSString *nsRedDotBuff; // @synthesize nsRedDotBuff;
@property(retain, nonatomic) NSString *nsTipIconUrl; // @synthesize nsTipIconUrl;
@property(retain, nonatomic) NSString *nsTipWording; // @synthesize nsTipWording;
- (id)pathForCache;
- (void)saveToCache;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

