//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MMCommon/MMObject.h>

#import "PBMessageObserverDelegate-Protocol.h"

@protocol WCFindFriendLogicDelegate;

@interface WCFindFriendLogic : MMObject <PBMessageObserverDelegate>
{
    id <WCFindFriendLogicDelegate> _delegate;
}

- (void).cxx_destruct;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (_Bool)checkMFriendList:(id)arg1 arrMobile:(id)arg2 arrEmail:(id)arg3;
- (void)dealloc;
- (void)handleRespForListMFriend:(id)arg1;
- (id)initWithDelegate:(id)arg1;

@end

