//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIView.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSString, UIImageView, UITableView;
@protocol WCMallOldTelephoneViewDelegate;

@interface WCMallOldTelephoneView : MMUIView <UITableViewDataSource, UITableViewDelegate>
{
    UITableView *m_oTelFilterTableView;
    id <WCMallOldTelephoneViewDelegate> m_delegate;
    _Bool _bNeedShowMask;
    unsigned int _historyCount;
    MMUIView *_backgroundView;
    UIImageView *_topMaskView;
    UIImageView *_bottomMaskView;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool bNeedShowMask; // @synthesize bNeedShowMask=_bNeedShowMask;
@property(retain, nonatomic) MMUIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) UIImageView *bottomMaskView; // @synthesize bottomMaskView=_bottomMaskView;
- (void)dealloc;
@property(nonatomic) unsigned int historyCount; // @synthesize historyCount=_historyCount;
- (id)initOldTelphoneViewWithFrame:(struct CGRect)arg1 delegate:(id)arg2;
- (void)initTableView;
- (void)initView;
@property(nonatomic) __weak id <WCMallOldTelephoneViewDelegate> m_delegate; // @synthesize m_delegate;
- (void)reloadTelFilterTableView;
- (void)resetWCMallTelListTableViewHeight;
- (void)scrollViewDidScroll:(id)arg1;
- (void)setMaskView;
@property(retain, nonatomic) UIImageView *topMaskView; // @synthesize topMaskView=_topMaskView;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)tapGesture;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

