//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class WCMallActivityInfo;

@interface WCMallGlobalActivity : NSObject
{
    WCMallActivityInfo *m_oActivityInfo;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WCMallActivityInfo *m_oActivityInfo; // @synthesize m_oActivityInfo;

@end

