//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class WCDataItem, WCMediaItem;

@interface WCMediaItemWrap : NSObject
{
    WCMediaItem *mediaItem;
    WCDataItem *parent;
    unsigned int index;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned int index; // @synthesize index;
- (id)init;
@property(retain, nonatomic) WCMediaItem *mediaItem; // @synthesize mediaItem;
@property(retain, nonatomic) WCDataItem *parent; // @synthesize parent;

@end

