//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSMutableDictionary;

@interface WCOperationSetting : NSObject <NSCoding>
{
    NSMutableDictionary *dicUserBigImageClickedCount;
    NSMutableDictionary *dicUserBigImageAddedCount;
    _Bool needWriteBack;
}

- (void).cxx_destruct;
- (void)addNewBigImageClickedCountForUser:(id)arg1 clickedCount:(unsigned long long)arg2;
- (void)addNewBigImageCountForUser:(id)arg1 addedCount:(unsigned long long)arg2;
@property(retain, nonatomic) NSMutableDictionary *dicUserBigImageAddedCount; // @synthesize dicUserBigImageAddedCount;
@property(retain, nonatomic) NSMutableDictionary *dicUserBigImageClickedCount; // @synthesize dicUserBigImageClickedCount;
- (void)encodeWithCoder:(id)arg1;
- (id)init;
- (id)initWithCoder:(id)arg1;
@property(nonatomic) _Bool needWriteBack; // @synthesize needWriteBack;

@end

