//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMTableViewCell.h"

@class UILabel;

@interface WCOutPhoneCell : MMTableViewCell
{
    UILabel *_phoneLabelLabel;
    UILabel *_phoneNumLabel;
}

- (void).cxx_destruct;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
@property(retain, nonatomic) UILabel *phoneLabelLabel; // @synthesize phoneLabelLabel=_phoneLabelLabel;
@property(retain, nonatomic) UILabel *phoneNumLabel; // @synthesize phoneNumLabel=_phoneNumLabel;

@end

