//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCBaseTextFieldItem.h"

@class TPIDKeyboardView;

@interface WCPayInputTextInfoCtrlItem : WCBaseTextFieldItem
{
    TPIDKeyboardView *keyboardView;
}

- (void).cxx_destruct;
- (void)autoRemarkKeyBoradType;
- (void)dealloc;
- (id)initWithTitle:(id)arg1 tip:(id)arg2 key:(id)arg3;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;

@end

