//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCPayBaseViewController.h"

#import "ILinkEventExt-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"
#import "WCActionSheetDelegate-Protocol.h"
#import "WCPayLQTOrderConfirmViewDelegate-Protocol.h"

@class MMTableView, MMUILabel, NSString, RichTextView, UIButton, UITextField, WCPayLQTOrderConfirmView;
@protocol WCPayLQTMoneyViewControllerDelegate;

@interface WCPayLQTMoneyViewController : WCPayBaseViewController <UITableViewDelegate, UITableViewDataSource, UITextFieldDelegate, ILinkEventExt, WCPayLQTOrderConfirmViewDelegate, WCActionSheetDelegate>
{
    _Bool _bCheckBoxSelect;
    id <WCPayLQTMoneyViewControllerDelegate> _delegate;
    MMTableView *_tableView;
    UIButton *_operationBtn;
    UITextField *_moneyTextField;
    MMUILabel *_invalidTipsLabel;
    RichTextView *_richTextView;
    WCPayLQTOrderConfirmView *_confirmView;
}

- (void).cxx_destruct;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
@property(nonatomic) _Bool bCheckBoxSelect; // @synthesize bCheckBoxSelect=_bCheckBoxSelect;
- (_Bool)canShowLQTProtocol;
- (void)checkBtnClick:(id)arg1;
@property(retain, nonatomic) WCPayLQTOrderConfirmView *confirmView; // @synthesize confirmView=_confirmView;
- (void)dealloc;
@property(nonatomic) __weak id <WCPayLQTMoneyViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)hideInvalidTipsLabel;
- (void)initInvalidTipsLabel;
@property(retain, nonatomic) MMUILabel *invalidTipsLabel; // @synthesize invalidTipsLabel=_invalidTipsLabel;
- (void)leftBarButtonClick;
- (_Bool)lqtProtocolCheck;
- (void)makeBtnCellContentView:(id)arg1;
- (void)makeInputContentView:(id)arg1;
- (id)makeProtocolContentView;
@property(retain, nonatomic) UITextField *moneyTextField; // @synthesize moneyTextField=_moneyTextField;
- (void)onLinkClicked:(id)arg1 withRect:(struct CGRect)arg2;
- (void)onOrderConfirmViewCancel;
- (void)onOrderConfirmViewPayWithEnPwd:(id)arg1;
@property(retain, nonatomic) UIButton *operationBtn; // @synthesize operationBtn=_operationBtn;
- (void)operationBtnClick;
- (void)refreshBalanceContent;
@property(retain, nonatomic) RichTextView *richTextView; // @synthesize richTextView=_richTextView;
@property(retain, nonatomic) MMTableView *tableView; // @synthesize tableView=_tableView;
- (void)setupContentView;
- (_Bool)shouldShowProfitWording;
- (void)showInvalidTipsLabelWithContent:(id)arg1;
- (void)showPwdConfirmViewWhenPreRedeemFundOk;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableViewBtnCellHeight;
- (double)tableViewBtnWithProtocolCellHeight;
- (double)tableViewInputContentCellHeight;
- (double)tableViewProfitContentHeight;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)textFieldDidChang:(id)arg1;
- (void)viewDidBePoped:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

