//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIView.h"

@class CMMotionManager, UIImage, UIImageView, UIScrollView;

@interface WCPanoramaImageView : MMUIView
{
    UIImage *_image;
    CMMotionManager *_motionManager;
    UIScrollView *_scrollView;
    UIImageView *_imageView;
    double _motionRate;
    long long _minimumXOffset;
    long long _maximumXOffset;
    struct CGRect _viewFrame;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 image:(id)arg2;
@property(nonatomic) long long maximumXOffset; // @synthesize maximumXOffset=_maximumXOffset;
@property(nonatomic) long long minimumXOffset; // @synthesize minimumXOffset=_minimumXOffset;
@property(retain, nonatomic) CMMotionManager *motionManager; // @synthesize motionManager=_motionManager;
@property(nonatomic) double motionRate; // @synthesize motionRate=_motionRate;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) struct CGRect viewFrame; // @synthesize viewFrame=_viewFrame;
- (void)startMonitoring;
- (void)stopMonitoring;

@end

