//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface WCPayCheckPayPwdByTokenRequest : NSObject
{
    NSString *m_nsPayPwd;
    NSString *m_nsToken;
    _Bool m_bResend;
}

- (void).cxx_destruct;
- (void)dealloc;
@property(nonatomic) _Bool m_bResend; // @synthesize m_bResend;
@property(retain, nonatomic) NSString *m_nsPayPwd; // @synthesize m_nsPayPwd;
@property(retain, nonatomic) NSString *m_nsToken; // @synthesize m_nsToken;

@end

