//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface WCRecommendAdInfo : NSObject
{
    NSString *snsXml;
    NSString *snsRecXml;
    NSString *snsRecInfo;
}

- (void).cxx_destruct;
- (id)description;
- (id)init;
@property(retain, nonatomic) NSString *snsRecInfo; // @synthesize snsRecInfo;
@property(retain, nonatomic) NSString *snsRecXml; // @synthesize snsRecXml;
@property(retain, nonatomic) NSString *snsXml; // @synthesize snsXml;

@end

