//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface WCSnsABTestTitle : NSObject
{
    NSString *showTitleFormat;
    _Bool hasUserNameKey;
    _Bool hasSexKey;
    NSString *maleKey;
    NSString *femailKey;
    NSString *defaultSexKey;
    NSString *richTextKey;
}

- (void).cxx_destruct;
- (id)description;
- (id)getShowTitle:(id)arg1;
- (id)init;
- (_Bool)parseTitleFormat:(id)arg1 priorTitleFormat:(id)arg2;
@property(retain, nonatomic) NSString *richTextKey; // @synthesize richTextKey;
- (_Bool)tryParseTitleFormat:(id)arg1;

@end

