//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "INewQQMailExt-Protocol.h"
#import "IQQMailExt-Protocol.h"
#import "MMMailContactSelectViewDelegate-Protocol.h"
#import "MailAttachmentControlViewDelegate-Protocol.h"
#import "MailContactFilterViewDelegate-Protocol.h"
#import "MailReceiverEditViewDelegate-Protocol.h"
#import "UIAlertViewDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "UIWebViewDelegate-Protocol.h"
#import "VerifyQQPwdMgrExt-Protocol.h"
#import "WCActionSheetDelegate-Protocol.h"

@class CMail, MMTableView, MMTimer, MailAttachmentControlView, MailContactFilterView, MailReceiverEditView, MailSubjectEditView, NSMutableArray, NSString, UIResponder, UIView, UIWebView;
@protocol WebMailViewDelegate;

@interface WebMailViewController : MMUIViewController <WCActionSheetDelegate, UITableViewDelegate, UITableViewDataSource, UINavigationControllerDelegate, UIAlertViewDelegate, UIScrollViewDelegate, UIWebViewDelegate, MMMailContactSelectViewDelegate, MailAttachmentControlViewDelegate, MailReceiverEditViewDelegate, MailContactFilterViewDelegate, IQQMailExt, INewQQMailExt, VerifyQQPwdMgrExt>
{
    MMTableView *m_tableView;
    MailContactFilterView *m_filterView;
    UIWebView *m_webView;
    MailReceiverEditView *m_receiverView;
    MailReceiverEditView *m_ccView;
    MailReceiverEditView *m_bccView;
    MailSubjectEditView *m_topicView;
    UIView *m_ccBccView;
    NSMutableArray *m_arrShowViews;
    MailAttachmentControlView *m_attachmentControlView;
    CMail *m_mail;
    NSMutableArray *m_arrReceiver;
    NSMutableArray *m_arrCc;
    NSMutableArray *m_arrBcc;
    NSMutableArray *m_arrAttachment;
    unsigned int m_uiMailType;
    NSString *m_nsSubject;
    NSString *m_nsMailHeader;
    int m_firstResponderStatus;
    int m_ccBccFlodStatus;
    MMTimer *m_autoSaveTimer;
    unsigned int m_firstResponderTag;
    double m_fKeyboardHeight;
    double m_defaultvisibleheight;
    NSMutableArray *m_arrAttachmentView;
    NSMutableArray *m_arrAllMailContacts;
    NSString *m_nsMailID;
    _Bool m_bFromReadMail;
    _Bool m_bFirstFixContectHeight;
    _Bool m_bPresentModal;
    NSMutableArray *m_nsChats;
    _Bool m_bIsSending;
    id <WebMailViewDelegate> m_delegate;
    _Bool m_rewritingDataSource;
    UIResponder *keyboardActiveInput;
}

- (void).cxx_destruct;
- (void)CheckCancel:(id)arg1;
- (void)OnGetAllMailContact:(id)arg1 ErrNo:(int)arg2;
- (void)OnReturn;
- (void)ReleaseTextField;
- (_Bool)SendBtnEnable;
- (void)SetWebViewMargin:(unsigned int)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (float)calculateTableViewHeight;
- (void)composeSend;
- (void)contactReturn:(id)arg1;
- (void)dealloc;
- (id)decodeFromPercentEscapeString:(id)arg1;
- (void)deleteDraft;
- (void)didReceiveMemoryWarning;
- (void)doSearch:(id)arg1;
- (void)fixFilterView;
- (id)getContent;
- (id)getFilterName:(id)arg1;
- (int)getFirstResponderStatusForRow:(long long)arg1;
- (int)getNextResponderStautsForFirstResponderStatus:(int)arg1;
- (id)getSelfWebMailContact;
- (id)getViewController;
- (id)getViewForFirstResponderStatus:(int)arg1;
- (void)handleGetOffsetFromJS:(id)arg1;
- (void)handleSetOffsetFromJS:(id)arg1;
- (long long)indexForView:(id)arg1;
- (id)init;
- (void)initAttaches;
- (void)initAutoSaveTimer;
- (void)initData;
- (void)initNotificationObservers;
- (void)initTableItemViews;
- (void)initView;
- (id)initWithMail:(id)arg1 withContent:(id)arg2 mailType:(unsigned int)arg3;
- (id)initWithMail:(id)arg1 withContent:(id)arg2 withSubject:(id)arg3;
@property(retain, nonatomic) UIResponder *keyboardActiveInput; // @synthesize keyboardActiveInput;
- (void)keyboardDidShow:(id)arg1;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)loadDraft;
@property(retain, nonatomic) NSMutableArray *m_arrAllMailContacts; // @synthesize m_arrAllMailContacts;
@property(nonatomic) _Bool m_bFromReadMail; // @synthesize m_bFromReadMail;
@property(nonatomic) _Bool m_bPresentModal; // @synthesize m_bPresentModal;
@property(nonatomic) double m_defaultvisibleheight; // @synthesize m_defaultvisibleheight;
@property(nonatomic) __weak id <WebMailViewDelegate> m_delegate; // @synthesize m_delegate;
@property(retain, nonatomic) NSString *m_nsMailHeader; // @synthesize m_nsMailHeader;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)onAddMailContact:(id)arg1;
- (void)onAutoSaveTimer;
- (void)onCancelButton;
- (void)onFirstResponderResigned;
- (void)onMailContactChanged:(id)arg1;
- (void)onMailContactDoubleClicked:(id)arg1;
- (void)onMailContactSelectDone:(id)arg1 userInfo:(id)arg2;
- (void)onMailReceiverEditViewHeightChanged:(id)arg1;
- (void)onSend;
- (void)onTextFieldChanged:(id)arg1;
- (void)onTextFieldFinishEdit:(id)arg1;
- (void)onTextFieldNextItem:(id)arg1;
- (void)rebuildTableView;
- (void)releaseAutoSaveTimer;
- (void)reloadTableView;
- (void)removeNotificationObservers;
- (void)responderDidBecomeActive:(id)arg1;
- (void)rewriteDataSource:(int)arg1;
- (void)saveDraft;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)setContent:(id)arg1;
- (void)setFirstRespondStatus:(int)arg1;
- (void)setMailTitle:(id)arg1;
- (void)setNextFirstRespondStatus:(int)arg1;
- (void)setccBccFlodStatus:(int)arg1;
- (void)staticReloadTableView;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)updateCurrentOffset;
- (void)updateRightBarButton;
- (void)uploadAttachment:(id)arg1 name:(id)arg2;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidBeDismissed:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

