//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WebviewJSEventHandlerBase.h"

#import "IContactMgrExt-Protocol.h"
#import "PBMessageObserverDelegate-Protocol.h"

@class MMTimer;

@interface WebViewJSEventHandler_quicklyAddContact : WebviewJSEventHandlerBase <PBMessageObserverDelegate, IContactMgrExt>
{
    _Bool _isWaitContactSync;
    MMTimer *_timerContactSync;
}

- (void).cxx_destruct;
- (void)CreateVerify:(id)arg1 andScene:(unsigned int)arg2 reportInfo:(id)arg3;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (void)callbackAddContactOK;
- (void)dealloc;
- (void)handleJSEvent:(id)arg1 HandlerFacade:(id)arg2 ExtraData:(id)arg3;
- (void)invalidateContactSyncTimer;
- (void)onModifyContact:(id)arg1;
- (void)onTimeoutContactSync:(id)arg1;
- (void)scheduleContactSyncTimer;

@end

