//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FTSJSEventDelegate-Protocol.h"
#import "WCCommentDetailViewControllerFBDelegate-Protocol.h"
#import "WSMusicDelegate-Protocol.h"

@class FTSWebSearchMgr, MMUIViewController, NSString;
@protocol WSJSEventHandleDelegate;

@interface WSJSEventHandler : NSObject <WCCommentDetailViewControllerFBDelegate, WSMusicDelegate, FTSJSEventDelegate>
{
    MMUIViewController *_baseViewController;
    id <WSJSEventHandleDelegate> _delegate;
    FTSWebSearchMgr *_webSearchMgr;
}

- (void).cxx_destruct;
@property(nonatomic) __weak MMUIViewController *baseViewController; // @synthesize baseViewController=_baseViewController;
- (void)dealloc;
@property(nonatomic) __weak id <WSJSEventHandleDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didFinishLoadWebView:(id)arg1;
- (void)enableSearchBar;
- (void)hideKeyboard;
- (void)notifyPageOfMusicStatusChanged:(id)arg1;
- (void)onClearHistoryOperation:(id)arg1;
- (void)onClickRecmdWord:(id)arg1;
- (void)onDeleteData;
- (void)onFailReceiveJson;
- (id)onGetBaseViewController;
- (void)onInsertHistoryOperation:(id)arg1;
- (id)onInsertWAWidgetWithParams:(id)arg1;
- (void)onLaunchDetailPage:(id)arg1;
- (void)onLaunchDetailPageForWeApp:(id)arg1;
- (void)onLaunchPage:(id)arg1 withParams:(id)arg2;
- (void)onMakePhoneCall:(id)arg1;
- (void)onOpenBrandContact:(id)arg1 withParams:(id)arg2;
- (void)onOpenContact:(id)arg1;
- (void)onOpenEmotionPage:(id)arg1;
- (void)onOpenMsgSession:(id)arg1;
- (void)onOpenSnsDetail:(id)arg1;
- (void)onOpenWAWidgetLogViewWithParams:(id)arg1;
- (void)onOpenWeAppPage:(id)arg1;
- (void)onPreSearch:(id)arg1 bizType:(unsigned long long)arg2;
- (void)onReceiveJson:(id)arg1;
- (void)onRemoveWAWidgetWithParams:(id)arg1;
- (void)onRequestLocalSuggestion:(id)arg1;
- (void)onSearchInputChanged:(id)arg1;
- (void)onSwitchSearchContext:(id)arg1;
- (void)onUpdateWAWidgetWithParams:(id)arg1;
- (void)onViewTypeChange:(id)arg1;
- (void)registerWSMusicHandler;
@property(retain, nonatomic) FTSWebSearchMgr *webSearchMgr; // @synthesize webSearchMgr=_webSearchMgr;
- (void)startMusicPlayer:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

