//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface WXGChatLogNetworkUtility : NSObject
{
}

+ (id)_getCorrectMaskWithIP:(id)arg1;
+ (id)currentHotSpotOrWifiSSID;
+ (_Bool)isBatteryChargeAndLevel:(float *)arg1;
+ (_Bool)isHotspotActivity;
+ (_Bool)isOnWifiOrHostSpotMode;
+ (_Bool)isSameNetGateWay:(id)arg1;
+ (_Bool)isSameWifi:(id)arg1 selfWifiName:(id *)arg2;

@end

