//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class WCTDatabase;

@interface WXGMigrationInfoDB : NSObject
{
    WCTDatabase *m_db;
}

- (void).cxx_destruct;
- (void)closeDB;
- (void)createSessionLastTimeTableWithDeviceID:(id)arg1;
- (void)dealloc;
- (id)getSessionInfoResultResultArrayWithDataInfo:(id)arg1 withTmpLastTime:(unsigned int)arg2 withDeviceID:(id)arg3;
- (unsigned int)getSessionLastTime:(id)arg1 withDeviceID:(id)arg2;
- (_Bool)hasMigrationWithDeviceID:(id)arg1;
- (_Bool)hasMigrationWithDeviceID:(id)arg1 withSessionName:(id)arg2;
- (id)init;
- (void)insertSession:(id)arg1 withBeginTime:(unsigned int)arg2 withEndTime:(unsigned int)arg3 withDeviceID:(id)arg4;
- (void)insertSession:(id)arg1 withLastTime:(unsigned int)arg2 withDeviceID:(id)arg3;
- (id)p_getSessionLastTimeTableWithDeviceID:(id)arg1;
- (id)p_getSessionTimeIntervalTableWithDeviceID:(id)arg1;
- (void)p_mergeTheTimeIntervalArray:(id)arg1;

@end

