//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDate;

@protocol WXGSelectTimeViewControllerDelegate <NSObject>
- (void)onSelectTimeViewCancel;
- (void)onSelectTimeViewCompleteWithBeginDate:(NSDate *)arg1 endDate:(NSDate *)arg2 selectAllTime:(_Bool)arg3 selectTextOnly:(_Bool)arg4;
@end

