//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface WXTalkComponent : NSObject
{
    struct WXTalkEngineAdapter *_engineAdapter;
    struct IMultiTalkMgr *_wxTalkEngine;
}

- (void)dealloc;
@property(nonatomic) struct WXTalkEngineAdapter *engineAdapter; // @synthesize engineAdapter=_engineAdapter;
- (void)getLocalCapInfo:(void **)arg1 capInfoLen:(int *)arg2 forNetType:(int)arg3;
- (id)init;
@property(nonatomic) struct IMultiTalkMgr *wxTalkEngine; // @synthesize wxTalkEngine=_wxTalkEngine;

@end

