//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MMCommon/MMService.h>

#import "IAppTrafficExt-Protocol.h"
#import "MMService-Protocol.h"

@class CleanTaskInfo, NSMutableArray, NSRecursiveLock, NSString, NSThread;

@interface CleanCacheService : MMService <MMService, IAppTrafficExt>
{
    NSMutableArray *_arrDoneTask;
    NSMutableArray *_arrWaitTask;
    CleanTaskInfo *_curTaskInfo;
    NSMutableArray *_arrSubFolderName;
    NSMutableArray *_arrSubFileName;
    NSThread *_taskThread;
    NSRecursiveLock *_lock;
    int _runStatus;
    unsigned int _cleanedTotalSize;
    unsigned int _receivedTotalSize;
}

+ (long long)randomIndex:(unsigned long long)arg1;
- (void).cxx_destruct;
- (void)addAutoCleanTask:(id)arg1;
- (void)asyncPause;
- (void)asyncStart;
- (_Bool)canAddTask:(id)arg1;
- (void)dealloc;
- (void)forceStop;
- (id)init;
- (void)onReceiveDataLen:(unsigned int)arg1;
- (void)onServiceEnterBackground;
- (void)onServiceEnterForeground;
- (void)onServiceTerminate;
- (void)reportCleanPerformance;
- (_Bool)shouldDeletePath:(id)arg1;
- (void)start;
- (void)threadFunc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

