//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MMCommon/MMObject.h>

#import "PBMessageObserverDelegate-Protocol.h"

@class NSMutableArray;
@protocol ContactInitLogicExt;

@interface ContactInitLogic : MMObject <PBMessageObserverDelegate>
{
    id <ContactInitLogicExt> m_delegate;
    NSMutableArray *m_usernames;
    NSMutableArray *m_failedUsernames;
    struct ContactInitSeqs m_contactInitSeqs;
    unsigned long long m_totalContactCount;
    unsigned long long m_finishedContactCount;
}

+ (_Bool)isContactInited;
+ (void)setContactInitedStatus:(_Bool)arg1;
- (void).cxx_destruct;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (void)checkIsSucceed;
- (void)doGetContactLogic;
- (void)handleGetContactsRsp:(id)arg1;
- (void)handleGetUsernamesRsp:(id)arg1;
- (id)initWithDelegate:(id)arg1;
- (_Bool)startContactInitLogic;
- (_Bool)tryGetContacts;
- (_Bool)tryGetUsernames;

@end

