//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class UIView;

@interface DropdownItem : UIButton
{
    UIView *_separatorView;
    long long subItemIndex;
}

- (void).cxx_destruct;
- (void)dealloc;
- (void)drawRoundRectRect:(struct CGRect)arg1;
- (void)layoutSubviews;
@property(nonatomic) long long subItemIndex; // @synthesize subItemIndex;

@end

