//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class CALayer, UIColor, UIView;

@protocol EditImageToolDelegate <NSObject>
@property(retain, nonatomic) UIColor *_lineColor;
@property(nonatomic) double _lineWidth;
@property(nonatomic) unsigned int _penCount;
- (void)drawLayer;

@optional
- (struct CGRect)addPathWithP2Point:(struct CGPoint)arg1 withP1Point:(struct CGPoint)arg2 withCPoint:(struct CGPoint)arg3;
- (CALayer *)createLayer:(struct CGRect)arg1;
- (UIView *)createView:(struct CGRect)arg1;
- (void)setInitialPoint:(struct CGPoint)arg1;
@end

