//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface EnterpriseSearchResultItem : NSObject
{
    unsigned int _matchField;
    NSString *_matchText;
    NSObject *_item;
}

- (void).cxx_destruct;
- (id)initWithObject:(id)arg1 matchField:(unsigned int)arg2 matchText:(id)arg3;
@property(retain, nonatomic) NSObject *item; // @synthesize item=_item;
@property(nonatomic) unsigned int matchField; // @synthesize matchField=_matchField;
@property(retain, nonatomic) NSString *matchText; // @synthesize matchText=_matchText;

@end

