//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MMCommon/MMObject.h>

@class FavoritesTagDB;

@interface FavoritesTagMgr : MMObject
{
    FavoritesTagDB *_favTagDB;
}

- (void).cxx_destruct;
- (void)deleteItemTagsByFavLocalId:(unsigned int)arg1;
- (id)getAllTags;
- (id)getItemTags:(unsigned int)arg1;
- (id)init;
- (void)initDB:(id)arg1;
- (void)updateItemTags:(id)arg1 byFavLocalId:(unsigned int)arg2;

@end

