//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIView.h"

@class FavoritesItemDataField, MMHeadImageView, MMUILabel, UILabel, UIView;
@protocol FavRecordNodeViewDelegate, RecordNodeDataSource;

@interface FavRecordBaseNodeView : MMUIView
{
    UILabel *m_srcTitleLabel;
    UIView *m_contentView;
    _Bool m_bIsLongPressHandled;
    double m_fContentHeight;
    id <FavRecordNodeViewDelegate> m_delegate;
    id <RecordNodeDataSource> dataSource;
    FavoritesItemDataField *favData;
    MMUILabel *m_srcTimeLabel;
    MMHeadImageView *m_headImg;
    UIView *m_sepLine;
}

+ (double)heightForData:(id)arg1;
- (void).cxx_destruct;
- (void)LongPressEvents;
- (void)addContentSubView;
@property(readonly, retain, nonatomic) id <RecordNodeDataSource> dataSource; // @synthesize dataSource;
@property(readonly, retain, nonatomic) FavoritesItemDataField *favData; // @synthesize favData;
- (void)initContentView;
- (void)initSrcTitle;
- (void)initView;
- (id)initWithDataSource:(id)arg1;
- (_Bool)isTouchInContentView:(id)arg1;
- (void)layoutSubviews;
@property(nonatomic) __weak id <FavRecordNodeViewDelegate> m_delegate; // @synthesize m_delegate;
- (void)onLongTouch;
- (void)onTouchCancel;
- (void)onTouchDown;
- (void)onTouchDownRepeat;
- (void)onTouchUpInside;
- (void)pressedEvents;
- (void)setNodeSize;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)updateContentSubview;
- (void)updateNodeWithTimePrefix:(id)arg1 headHidden:(_Bool)arg2 bottomLineHidden:(_Bool)arg3;

@end

