//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "GameCenterMsgCenterCellDataSource-Protocol.h"
#import "GameCenterMsgCenterCellViewDelegate-Protocol.h"
#import "MMRefreshTableFooterDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "WCActionSheetDelegate-Protocol.h"
#import "tableViewDelegate-Protocol.h"

@class MMTableView, NSMutableArray, NSMutableDictionary, NSString, UIView, WCTimeLineFooterView;

@interface GameCenterMsgCenterViewController : MMUIViewController <UITableViewDataSource, UITableViewDelegate, tableViewDelegate, WCActionSheetDelegate, MMRefreshTableFooterDelegate, GameCenterMsgCenterCellDataSource, GameCenterMsgCenterCellViewDelegate>
{
    _Bool _hasMore;
    _Bool _showHeader;
    int _sourceScene;
    MMTableView *_msgTableView;
    WCTimeLineFooterView *_footerView;
    NSMutableArray *_readMsgList;
    NSMutableArray *_unReadMsgList;
    UIView *_splitView;
    NSMutableDictionary *_cellCache;
    NSMutableDictionary *_cellHeightCache;
    long long _msgListType;
    NSString *_msgCenterSettingUrl;
}

- (void).cxx_destruct;
- (void)MMRefreshTableFooterDidTriggerRefresh:(id)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
@property(retain, nonatomic) NSMutableDictionary *cellCache; // @synthesize cellCache=_cellCache;
- (void)cellForView:(id)arg1;
@property(retain, nonatomic) NSMutableDictionary *cellHeightCache; // @synthesize cellHeightCache=_cellHeightCache;
- (void)didReceiveMemoryWarning;
@property(retain, nonatomic) WCTimeLineFooterView *footerView; // @synthesize footerView=_footerView;
- (id)getCellContentView:(id)arg1;
- (long long)getCurrentMsgListType;
- (id)getFirstPageReadMsgList:(unsigned int)arg1;
- (id)getMsgItem:(long long)arg1 MsgIndex:(long long *)arg2 isInUnRead:(_Bool *)arg3;
- (long long)getRowNum;
- (id)getSplitView;
- (unsigned int)getUnReadMsgList;
@property(nonatomic) _Bool hasMore; // @synthesize hasMore=_hasMore;
- (void)initCurrentMsgListType;
- (void)initFirstPageMsgList;
- (void)initHeaderSetting;
- (void)initHeaderView;
- (void)initView;
- (id)initWithSourceScene:(int)arg1;
- (int)jumpToDetailView:(id)arg1;
- (void)jumpToWebView:(id)arg1;
- (void)jumpWithPosition:(unsigned int)arg1 JumpInfo:(id)arg2 MsgItem:(id)arg3;
- (void)loadReadMsgNextPageList:(unsigned int)arg1;
@property(retain, nonatomic) NSString *msgCenterSettingUrl; // @synthesize msgCenterSettingUrl=_msgCenterSettingUrl;
@property(nonatomic) long long msgListType; // @synthesize msgListType=_msgListType;
@property(retain, nonatomic) MMTableView *msgTableView; // @synthesize msgTableView=_msgTableView;
- (void)onClearMsgList;
- (void)onContentPicClick:(id)arg1;
- (void)onLoadMore;
- (void)onMergeUserImageClick:(id)arg1 Url:(id)arg2;
- (void)onMessageCardClick:(id)arg1;
- (void)onMsgCenterHeaderBtnClicked;
- (void)onSecondLineClick:(id)arg1;
- (void)onSourceClick:(id)arg1;
- (void)onUserHeadClick:(id)arg1;
- (void)onUserNickNameClick:(id)arg1;
@property(retain, nonatomic) NSMutableArray *readMsgList; // @synthesize readMsgList=_readMsgList;
- (void)scrollViewDidScroll:(id)arg1;
@property(nonatomic) _Bool showHeader; // @synthesize showHeader=_showHeader;
@property(nonatomic) int sourceScene; // @synthesize sourceScene=_sourceScene;
@property(retain, nonatomic) UIView *splitView; // @synthesize splitView=_splitView;
@property(retain, nonatomic) NSMutableArray *unReadMsgList; // @synthesize unReadMsgList=_unReadMsgList;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (void)updateTableFooterView;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

