//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "PBMessageObserverDelegate-Protocol.h"
#import "UIAlertViewDelegate-Protocol.h"
#import "WCActionSheetDelegate-Protocol.h"

@class CAttach, ForwardMessageLogicController, MMMPMoviePlayerController, MMProgressView, NSString, UIButton, UIDocumentInteractionController, UILabel;
@protocol MailAttachDelegate;

@interface MailAttachDetailViewController : MMUIViewController <UIAlertViewDelegate, WCActionSheetDelegate, PBMessageObserverDelegate>
{
    CAttach *m_oAttach;
    NSString *m_nsMailID;
    _Bool m_bDownloading;
    MMProgressView *m_viewProgress;
    UILabel *m_labProgress;
    UIButton *m_btnCancelDownload;
    UIButton *m_btnDownload;
    UILabel *m_labCannotOpen;
    UIButton *m_btnPreview;
    UIButton *m_btnOpenByApp;
    id <MailAttachDelegate> m_delegate;
    _Bool m_bPreview;
    unsigned int m_uiPreviewType;
    UIDocumentInteractionController *m_vcDocument;
    unsigned int m_uiStartPos;
    unsigned int m_uiDataLen;
    _Bool m_bViewDidAppear;
    unsigned int m_uiEventID;
    MMMPMoviePlayerController *_moviePlayerController;
    NSString *m_tmpFilePath;
    ForwardMessageLogicController *m_forwardLogic;
}

- (void).cxx_destruct;
- (void)CreateDownloadEvent;
- (id)GetFileImgByFileExt;
- (id)GetFilePath;
- (unsigned int)GetPreviewType;
- (id)GetTmpFilePath;
- (void)InitDownload:(_Bool)arg1;
- (void)InitPreview;
- (_Bool)IsPreviewFile;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (void)OnOpenByApp;
- (void)OnOperate:(id)arg1;
- (void)OnPreviewCompress;
- (void)OnReturn;
- (void)SafeDeleteDocument;
- (void)SetDownloadHide:(_Bool)arg1;
- (void)SetProgress:(unsigned int)arg1;
- (void)SetProgressHide:(_Bool)arg1;
- (void)ShowDownloadBtn;
- (void)ShowProgressView;
- (void)StartDownload;
- (void)StopDownload;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)dealloc;
- (void)didAppear;
- (void)documentInteractionController:(id)arg1 didEndSendingToApplication:(id)arg2;
- (id)getCurrentViewController;
- (id)init;
@property(nonatomic) __weak id <MailAttachDelegate> m_delegate; // @synthesize m_delegate;
@property(retain, nonatomic) NSString *m_nsMailID; // @synthesize m_nsMailID;
@property(retain, nonatomic) CAttach *m_oAttach; // @synthesize m_oAttach;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

