//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface MMDumpReportData : NSObject
{
    NSMutableArray *m_uploadFilesArray;
    unsigned long long m_dumpType;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned long long m_dumpType; // @synthesize m_dumpType;
@property(retain, nonatomic) NSMutableArray *m_uploadFilesArray; // @synthesize m_uploadFilesArray;

@end

