//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMTableViewCell.h"

#import "CAAnimationDelegate-Protocol.h"

@class NSIndexPath, NSMutableArray, NSString, UIColor, UIGestureRecognizer, UIImageView, UIView;

@interface MMMultiMenuTableViewCell : MMTableViewCell <CAAnimationDelegate>
{
    UIView *_menuContentView;
    UIView *_actualContentView;
    UIGestureRecognizer *_panGestureRecognizer;
    double _initialTouchPositionX;
    _Bool _shouldDisplayContextMenuView;
    _Bool _contextMenuHidden;
    _Bool _shouldDisplayRightSwipeTips;
    UIImageView *_copyedBackgroundView;
    _Bool m_bIsNeedUpdateMenu;
    _Bool m_bUseDynamicSize;
    _Bool bNotAddDeleteBtn;
    _Bool _contextMenuEnabled;
    NSIndexPath *_indexPath;
    NSMutableArray *_arrMenuItems;
    UIColor *_menuBackgroundColor;
}

- (void).cxx_destruct;
- (id)FindTableView:(id)arg1;
- (id)accessibilityElementAtIndex:(long long)arg1;
- (long long)accessibilityElementCount;
- (id)animation;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
@property(retain, nonatomic) NSMutableArray *arrMenuItems; // @synthesize arrMenuItems=_arrMenuItems;
- (void)checkAndAddDeleteItem;
- (id)contentView;
@property(nonatomic) _Bool contextMenuEnabled; // @synthesize contextMenuEnabled=_contextMenuEnabled;
- (void)forceHideMenuOptionsAnimated:(_Bool)arg1;
- (void)forceHideMenuOptionsAnimated:(_Bool)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (double)getCurrentWidth;
- (void)handlePan:(id)arg1;
- (void)hideMenuOptionsAnimated:(_Bool)arg1;
- (long long)indexOfAccessibilityElement:(id)arg1;
@property(retain, nonatomic) NSIndexPath *indexPath; // @synthesize indexPath=_indexPath;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (_Bool)isMenuHidden;
- (_Bool)isPointInMenu:(struct CGPoint)arg1;
- (void)layoutSubviews;
@property(retain, nonatomic) UIColor *menuBackgroundColor; // @synthesize menuBackgroundColor=_menuBackgroundColor;
- (void)onButtonClicked:(id)arg1;
- (void)onClearBackgroundView;
- (void)prepareForReuse;
- (void)resetActionContentView;
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setMenuItemCaption:(long long)arg1 withCaption:(id)arg2;
- (void)setMenuItemsWithDefaultDeleteBtn:(id)arg1;
- (void)setMenuItemsWithNoDeleteBtn:(id)arg1;
- (void)setMenuOptionsViewHidden:(_Bool)arg1 animated:(_Bool)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)showRightSwipeTips;
- (void)updateMenuView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

