//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIScrollView.h"

#import "IMMAssetICloudExt-Protocol.h"
#import "MMAssetPickerBrowserViewProtocol-Protocol.h"
#import "SightAssetPreviewViewDelegate-Protocol.h"

@class AVAsset, MMAssetInfo, MMAssetPickerBrowserStateInfo, NSString, NSURL, SightAssetPreviewView, SightDraft, UIButton, UIImageView, UILabel, UIView;
@protocol MMAssetPickerBrowserViewDelegate, MMImagePickerControlCenter;

@interface MMVideoPreviewBrowserView : MMUIScrollView <IMMAssetICloudExt, SightAssetPreviewViewDelegate, MMAssetPickerBrowserViewProtocol>
{
    NSURL *m_originUrl;
    AVAsset *m_avAsset;
    NSURL *_videoOutputURL;
    SightDraft *_sightDraft;
    _Bool _isPlaying;
    _Bool _isSending;
    UIView *_maskView;
    SightAssetPreviewView *_playerView;
    UIButton *_playBigButton;
    UIImageView *m_icloudImageIcon;
    UILabel *m_icloudLabel;
    UIImageView *m_thumbImageView;
    id <MMImagePickerControlCenter> controlCenter;
    MMAssetInfo *assetInfo;
    id <MMAssetPickerBrowserViewDelegate> browserDelegate;
    MMAssetPickerBrowserStateInfo *m_stateInfo;
}

- (void).cxx_destruct;
- (void)OnPlay:(id)arg1;
@property(retain, nonatomic) MMAssetInfo *assetInfo; // @synthesize assetInfo;
@property(nonatomic) __weak id <MMAssetPickerBrowserViewDelegate> browserDelegate; // @synthesize browserDelegate;
- (void)changePlayStatus:(_Bool)arg1 needNotify:(_Bool)arg2;
- (void)checkVideo;
@property(nonatomic) __weak id <MMImagePickerControlCenter> controlCenter; // @synthesize controlCenter;
- (void)dealloc;
- (void)initData;
- (void)initMaskView;
- (void)initPlayerView;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)loadAsset;
- (void)onAssetVideoDonwloadFailed:(id)arg1;
- (void)onAssetVideoDownloadProgress:(double)arg1 assetUrl:(id)arg2;
- (void)onBeginToChangePage;
- (void)onGetVideoAssetFinishedWithAsset:(id)arg1 url:(id)arg2;
- (void)onSingleTap:(id)arg1;
@property(readonly, nonatomic) SightAssetPreviewView *playerView;
- (void)showThumbImageViewWithThumb:(id)arg1;
- (void)sightAssetPreviewView:(id)arg1 didFailWithError:(id)arg2;
- (void)sightAssetPreviewViewDidFinishPreparing:(id)arg1;
- (void)sightAssetPreviewViewPlaybackDidReachEnd:(id)arg1;
@property(readonly, nonatomic) MMAssetPickerBrowserStateInfo *stateInfo; // @synthesize stateInfo=m_stateInfo;
- (void)systemResigned:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

