//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSArray.h>

@interface NSArray (DeepSearch)
- (id)objectForDeepKey:(id)arg1;
- (id)objectForKeyPath:(id)arg1;
- (void)removeObjectForDeepKey:(id)arg1;
- (void)removeObjectForKeyPath:(id)arg1;
- (void)setObject:(id)arg1 forDeepKey:(id)arg2;
- (void)setObject:(id)arg1 forKeyPath:(id)arg2;
@end

