//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSURL.h>

@interface NSURL (NSURL_WechatUrl)
- (id)getUrlPartAfterSharp;
- (id)hostPort;
- (_Bool)isHostPathHasPrefixWithConfigKey:(id)arg1 defaultValue:(id)arg2;
- (_Bool)isNeedForceSyncA8Key;
- (_Bool)isOAuthUrl;
- (_Bool)isWechatRedirect;
@end

