//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class QBASIHTTPRequest;

@protocol QBASIProgressDelegate <NSObject>

@optional
- (void)request:(QBASIHTTPRequest *)arg1 didReceiveBytes:(long long)arg2;
- (void)request:(QBASIHTTPRequest *)arg1 didSendBytes:(long long)arg2;
- (void)request:(QBASIHTTPRequest *)arg1 incrementDownloadSizeBy:(long long)arg2;
- (void)request:(QBASIHTTPRequest *)arg1 incrementUploadSizeBy:(long long)arg2;
- (void)setProgress:(float)arg1;
@end

