//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSURLProtocol;

@interface QBProtocolWorker : NSObject
{
    NSURLProtocol *_protocol;
}

+ (id)qbProxyCanonicalRequestForRequest:(id)arg1;
+ (id)qbProxyProtocolAddCustomHTTPHeader:(id)arg1;
+ (_Bool)qbProxyProtocolCanInitWithRequest:(id)arg1 isQBWebViewRequest:(_Bool)arg2;
- (void).cxx_destruct;
@property(nonatomic) __weak NSURLProtocol *protocol; // @synthesize protocol=_protocol;
- (void)qbProxyProtocolDidFailWithError:(id)arg1;
- (void)qbProxyProtocolDidFinishLoading;
- (void)qbProxyProtocolDidFinishLoadingWithCached:(id)arg1;
- (void)qbProxyProtocolDidInitialized;
- (id)qbProxyProtocolDidReceiveData:(id)arg1;
- (_Bool)qbProxyProtocolDidReceiveResponse:(inout id *)arg1 error:(id *)arg2;
- (void)qbProxyProtocolDidStartLoading;
- (void)qbProxyProtocolDidStopLoading;
- (_Bool)qbProxyProtocolShouldStartLoading;
- (id)qbProxyProtocolWillSendRequest:(id)arg1 redirectResponse:(id)arg2;

@end

