//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseScanLogicController.h"

#import "CameraScannerStatusExt-Protocol.h"
#import "GetA8KeyLogicDelegate-Protocol.h"
#import "NewQRCodeScannerDelegate-Protocol.h"
#import "ScanBarcodeExt-Protocol.h"
#import "ScanQRCodeUrlPrefixHandlerDelegate-Protocol.h"
#import "UIAlertViewDelegate-Protocol.h"
#import "UIImagePickerControllerDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"

@class GetA8KeyLogic, NSObject, NSOperationQueue, NSString, NewQRCodeScanner, ScanQRCodeUrlPrefixRule, UIViewController;
@protocol OS_dispatch_semaphore;

@interface ScanQRCodeLogicController : BaseScanLogicController <ScanQRCodeUrlPrefixHandlerDelegate, CameraScannerStatusExt, NewQRCodeScannerDelegate, UIImagePickerControllerDelegate, UINavigationControllerDelegate, UIAlertViewDelegate, GetA8KeyLogicDelegate, ScanBarcodeExt>
{
    NewQRCodeScanner *_scanner;
    _Bool _hasCamera;
    GetA8KeyLogic *_logic;
    NSString *_desc;
    _Bool _hasFoundCode;
    NSString *_loadingText;
    NSString *_alertText;
    _Bool _showingMyQRCode;
    _Bool _scanOnePictureMode;
    NSOperationQueue *_scanPicOperationQueue;
    NSObject<OS_dispatch_semaphore> *_semaphore;
    _Bool _bIsScanFromAlbumImage;
    _Bool _hasReported;
    float _maxAreaRatio;
    _Bool _bNeedCameraScan;
    unsigned int fromScene;
    unsigned int _m_sourceType;
    NSString *_picUrl4Stat;
    NSString *_picEncKey4Stat;
    NSString *_m_sourceInfo;
    NSString *_m_weappSourceInfo;
    ScanQRCodeUrlPrefixRule *_m_urlPrefixRule;
    UIViewController *_m_viewController;
}

+ (id)shareScanOnePicSerialQueue;
- (void).cxx_destruct;
- (void)NewQRCodeScanner:(id)arg1 didScanResult:(id)arg2 type:(id)arg3 version:(int)arg4;
- (void)OnSendBarcode:(id)arg1 Err:(int)arg2;
- (void)dealloc;
@property(retain, nonatomic) NSString *desc; // @synthesize desc=_desc;
- (void)doScanQRCode:(id)arg1;
@property(nonatomic) unsigned int fromScene; // @synthesize fromScene;
- (id)getAlertText;
- (struct CGRect)getDrawCropRect;
- (id)getInfoText;
- (id)getIntroButtonTitle;
- (float)getIntroButtonTopPadding;
- (id)getIntroDesctiption;
- (id)getIntroTitle;
- (id)getLoadingText;
- (float)getPreviewScale;
- (id)getResultData;
- (id)getResultType;
- (_Bool)getScanResult:(double)arg1;
@property(nonatomic) _Bool hasFoundCode; // @synthesize hasFoundCode=_hasFoundCode;
- (id)initWithViewController:(id)arg1 CodeType:(int)arg2;
- (id)initWithViewController:(id)arg1 CodeType:(int)arg2 needCameraScan:(_Bool)arg3;
- (_Bool)isFoundWeAppWXCode;
@property(retain, nonatomic) NSString *m_sourceInfo; // @synthesize m_sourceInfo=_m_sourceInfo;
@property(nonatomic) unsigned int m_sourceType; // @synthesize m_sourceType=_m_sourceType;
@property(retain, nonatomic) ScanQRCodeUrlPrefixRule *m_urlPrefixRule; // @synthesize m_urlPrefixRule=_m_urlPrefixRule;
@property(nonatomic) __weak UIViewController *m_viewController; // @synthesize m_viewController=_m_viewController;
@property(retain, nonatomic) NSString *m_weappSourceInfo; // @synthesize m_weappSourceInfo=_m_weappSourceInfo;
- (void)onCameraScannerViewDidInit;
- (void)onClickErrorAlertConfirm;
- (void)onDetectQRCode:(_Bool)arg1 areaRatio:(float)arg2;
- (void)onGetA8KeyEnd;
- (void)onGetA8KeyResultType:(unsigned int)arg1;
- (void)onGetA8KeyStart;
- (void)onGetProductInfoEnd;
- (void)onGetProductInfoHandleEnd;
- (void)onGetProductInfoStart;
- (void)onGotBarcode:(id)arg1 Type:(id)arg2;
- (void)onIntroButtonClicked;
- (void)onNeedStartScan;
- (void)onRotate;
- (void)onScanQRCodeUrlPrefixHandlerEnd;
- (id)onScanQRCodeUrlPrefixHandlerRequestViewController;
- (void)onScanQRCodeUrlPrefixHandlerScanFinish;
- (void)onScanQRCodeUrlPrefixHandlerStart;
- (void)onScanQRCodeUrlPrefixHandlerWithErrorMsg:(id)arg1;
- (void)onSearchContactEnd;
- (void)onSearchContactHandleEnd;
- (void)onSearchContactStart;
@property(retain, nonatomic) NSString *picEncKey4Stat; // @synthesize picEncKey4Stat=_picEncKey4Stat;
@property(retain, nonatomic) NSString *picUrl4Stat; // @synthesize picUrl4Stat=_picUrl4Stat;
- (void)releaseSemaphore;
- (void)reportAfterCameraViewControlelrExit;
- (void)reportEngineStatWithScene:(unsigned int)arg1;
- (void)reportPrefixHandlerFailedCount;
@property(readonly, nonatomic) int scanCodeType;
- (void)scanOnePicture:(id)arg1;
- (void)setCropRect;
- (void)setViewController:(id)arg1;
- (_Bool)shouldDoAnimationWhenDismiss;
- (_Bool)shouldPopFromStack;
- (_Bool)shouldShowIntroButton;
- (void)showScanResult;
- (void)startLoadingCheck;
- (void)startLoadingSearch;
- (void)startScan;
- (void)stopScan;
- (void)tryScanOnePicture:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

