//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MMCommon/MMService.h>

#import "MMService-Protocol.h"

@class NSString;

@interface ScanAppSpaceSizeService : MMService <MMService>
{
    _Bool _hasAppSpaceSize;
    int _runStatus;
    long long _appSpaceSize;
    long long _scannedFileCount;
}

@property long long appSpaceSize; // @synthesize appSpaceSize=_appSpaceSize;
- (void)asyncStartTask;
- (void)asyncStopTask;
- (void)folderSizeAtPath:(const char *)arg1;
@property(readonly) _Bool hasAppSpaceSize; // @synthesize hasAppSpaceSize=_hasAppSpaceSize;
- (id)init;
- (void)onNotifyAppSpaceSize;
- (void)onScanTaskFinished;
- (void)onScanTaskUpdateProgress;
- (void)onServiceTerminate;
- (_Bool)reAsyncStartTask;
@property(readonly) int runStatus; // @synthesize runStatus=_runStatus;
@property(readonly) long long scannedFileCount; // @synthesize scannedFileCount=_scannedFileCount;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

