//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SharePreConfirmView;

@protocol SharePreConfirmViewDelegate <NSObject>

@optional
- (void)OnSharePreConfirmViewBackToApp:(SharePreConfirmView *)arg1;
- (void)OnSharePreConfirmViewCancel:(SharePreConfirmView *)arg1;
- (void)OnSharePreConfirmViewDidHide:(SharePreConfirmView *)arg1;
- (void)OnSharePreConfirmViewError:(SharePreConfirmView *)arg1;
- (void)OnSharePreConfirmViewSend:(SharePreConfirmView *)arg1;
- (void)OnSharePreConfirmViewStayAtWeChat:(SharePreConfirmView *)arg1;
@end

