//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FavStreamVideoItem, NSString;

@interface SimpleSightInfo : NSObject
{
    int _duration;
    int _type;
    int _illegalType;
    NSString *_dataPath;
    NSString *_thumbPath;
    FavStreamVideoItem *_streamVideoItem;
    NSString *_statExtStr;
    long long _dataSize;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *dataPath; // @synthesize dataPath=_dataPath;
@property(nonatomic) long long dataSize; // @synthesize dataSize=_dataSize;
@property(nonatomic) int duration; // @synthesize duration=_duration;
@property(nonatomic) int illegalType; // @synthesize illegalType=_illegalType;
@property(retain, nonatomic) NSString *statExtStr; // @synthesize statExtStr=_statExtStr;
@property(retain, nonatomic) FavStreamVideoItem *streamVideoItem; // @synthesize streamVideoItem=_streamVideoItem;
@property(retain, nonatomic) NSString *thumbPath; // @synthesize thumbPath=_thumbPath;
@property(nonatomic) int type; // @synthesize type=_type;

@end

