//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, SystemMsgTextWrap, UIImage, UIView;

@interface SystemMsgWrap : NSObject
{
    _Bool _m_enableClose;
    _Bool _m_closeButtonTransparent;
    SystemMsgTextWrap *_m_title;
    SystemMsgTextWrap *_m_description;
    UIImage *_m_backgroundImage;
    UIView *_m_backgroundView;
    NSString *_m_url;
    NSString *_m_backupURL;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIImage *m_backgroundImage; // @synthesize m_backgroundImage=_m_backgroundImage;
@property(retain, nonatomic) UIView *m_backgroundView; // @synthesize m_backgroundView=_m_backgroundView;
@property(retain, nonatomic) NSString *m_backupURL; // @synthesize m_backupURL=_m_backupURL;
@property(nonatomic) _Bool m_closeButtonTransparent; // @synthesize m_closeButtonTransparent=_m_closeButtonTransparent;
@property(retain, nonatomic) SystemMsgTextWrap *m_description; // @synthesize m_description=_m_description;
@property(nonatomic) _Bool m_enableClose; // @synthesize m_enableClose=_m_enableClose;
@property(retain, nonatomic) SystemMsgTextWrap *m_title; // @synthesize m_title=_m_title;
@property(retain, nonatomic) NSString *m_url; // @synthesize m_url=_m_url;

@end

