//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSString, TrustedFriendsLogic;

@protocol TrustedFriendsLogicDelegate <NSObject>
- (void)didAddTrustedFriendsLocally:(TrustedFriendsLogic *)arg1 contacts:(NSArray *)arg2;
- (void)didFailedCGI:(unsigned int)arg1 error:(unsigned int)arg2 msg:(NSString *)arg3;
- (void)didFinishGetTrustedFriends:(TrustedFriendsLogic *)arg1 contacts:(NSArray *)arg2;
- (void)didFinishSyncTrustedFriends:(TrustedFriendsLogic *)arg1 contacts:(NSArray *)arg2;
- (void)didRemoveTrustedFriendsLocally:(TrustedFriendsLogic *)arg1 contacts:(NSArray *)arg2;
- (void)didStartCGI:(unsigned int)arg1;
@end

