//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MMCommon/MMService.h>

#import "MMConfigMgrExt-Protocol.h"
#import "MMService-Protocol.h"
#import "PBMessageObserverDelegate-Protocol.h"

@class NSMutableArray, NSMutableDictionary, NSMutableSet, NSObject, NSString;
@protocol OS_dispatch_queue;

@interface WAContactMgr : MMService <MMConfigMgrExt, PBMessageObserverDelegate, MMService>
{
    NSObject<OS_dispatch_queue> *_worker_queue;
    NSMutableDictionary *_dicContactCache;
    NSMutableDictionary *_dicAppid2UsernameCache;
    NSMutableArray *_arrSingleAttrSyncWait;
    NSMutableArray *_arrSingleAttrSyncRequest;
    unsigned int _singleAttrSyncRequestInterval;
    NSMutableArray *_arrBatchAttrSyncWait;
    NSMutableSet *_setBatchAttrSyncRequest;
    unsigned int _batchAttrSyncRequestInterval;
}

- (void).cxx_destruct;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (void)batchUpdateWeAppContact:(id)arg1;
- (void)checkBatchWxaAttrSyncWaitQueue;
- (_Bool)checkIsInQueue:(id)arg1 withTask:(id)arg2;
- (_Bool)checkIsInSingleRequestingQueue:(id)arg1;
- (_Bool)checkIsInSingleWaitingQueue:(id)arg1;
- (void)checkWxaAttrSyncWaitQueue;
- (void)dealloc;
- (void)deleteWeAppContactList:(id)arg1;
- (id)getAllWeAppContact;
- (id)getContactFromCache:(id)arg1;
- (id)getContactFromCacheWithAppid:(id)arg1;
- (id)getContactFromCacheWithKey:(id)arg1 type:(unsigned long long)arg2;
- (id)getNewContactWithUserName:(id)arg1 bizAttr:(id)arg2;
- (id)getUsernameForAppid:(id)arg1;
- (id)getWeAppContact:(id)arg1;
- (id)getWeAppContactWithKey:(id)arg1 type:(unsigned long long)arg2;
- (id)init;
- (_Bool)isKeyValidWithKey:(id)arg1 keyType:(unsigned long long)arg2;
- (void)loadWxaAttrSyncRequestInterval;
- (void)mainThread_batchUpdateWeAppContact:(id)arg1;
- (void)mainThread_updateWeAppContact:(id)arg1;
- (void)mainthread_callExtensionDeleteContact:(id)arg1;
- (void)mainthread_callExtensionModifyContact:(id)arg1;
- (void)mainthread_callExtensionModifyContactList:(id)arg1;
- (void)markWaitTaskBeForcedUpdated:(id)arg1;
- (_Bool)modifyHeadImageStatus:(id)arg1 withUserName:(id)arg2;
- (_Bool)modifyWxAppOptWithBitMask:(unsigned int)arg1 bitValue:(unsigned int)arg2 userName:(id)arg3;
- (void)notifyContactListModify:(id)arg1;
- (void)onMMDynamicConfigUpdated;
- (void)onResponseBatchWxaAttrSync:(id)arg1;
- (void)onResponseWxaAttrSync:(id)arg1;
- (void)onServiceClearData;
- (void)onServiceInit;
- (void)onServiceReloadData;
- (void)processBatchWxaAttrSyncResponse:(id)arg1 completeHandlerOnMainThread:(CDUnknownBlockType)arg2;
- (void)processWxaAttrSyncResponse:(id)arg1 withRequest:(id)arg2 completeHandlerOnMainThread:(CDUnknownBlockType)arg3;
- (void)removeContactListInCache:(id)arg1;
- (void)removeUpdateTask:(id)arg1;
- (_Bool)requestBatchWxaAttrSync:(id)arg1 versionList:(id)arg2;
- (_Bool)requestWxaAttrSync:(id)arg1;
- (void)setContactListToCache:(id)arg1;
- (void)setHeadImageStatusForNewContact:(id)arg1 withOldContact:(id)arg2;
- (void)updateContact:(id)arg1 withBizAttr:(id)arg2;
- (void)updateContactCacheAndCallModifyContact:(id)arg1;
- (_Bool)updateContactListToDBAndCache:(id)arg1;
- (void)updateWeAppContact:(id)arg1;
- (void)updateWeAppContact:(id)arg1 isForce:(_Bool)arg2;
- (void)updateWeAppContactWithAppid:(id)arg1;
- (void)updateWeAppContactWithAppid:(id)arg1 isForce:(_Bool)arg2;
- (void)updateWeAppContactWithKey:(id)arg1 updateType:(unsigned long long)arg2;
- (void)updateWeAppContactWithKey:(id)arg1 updateType:(unsigned long long)arg2 isForce:(_Bool)arg3;
- (void)workThread_processBatchWxaAttrSyncResponse:(id)arg1 completeHandlerOnMainThread:(CDUnknownBlockType)arg2;
- (void)workThread_processWxaAttrSyncResponse:(id)arg1 withUserName:(id)arg2 completeHandlerOnMainThread:(CDUnknownBlockType)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

