//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MMCommon/MMObject.h>

@interface WASearchUtil : MMObject
{
}

+ (id)decodedQueryOfUrl:(id)arg1;
+ (id)dirForDefaultH5;
+ (id)dirForWeAppUpdatedSearchH5;
+ (unsigned int)getVersion;
+ (unsigned int)getVersionForDefaultH5;
+ (unsigned int)getVersionForUpdateH5;
+ (id)makeDictionaryFromPath:(id)arg1;
+ (id)pathForDefaultH5;
+ (id)pathForIOS8WKH5;
+ (id)pathForUpdatedH5;
+ (id)pathForWeAppSearchDir;
+ (id)pathForWeAppSearchH5;
+ (id)pathOfUrl:(id)arg1;
+ (void)reloadDefaultConfig;
+ (void)reloadDownloadConfig;
+ (void)removeWeAppUpdatedH5;
+ (unsigned int)uint32ForKey:(id)arg1 inParam:(id)arg2;
+ (unsigned long long)uint64ForKey:(id)arg1 inParam:(id)arg2;

@end

