//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "WCTTableCoding-Protocol.h"

@class NSMutableArray, NSString, WCCardPkgMsgActivity, WCCardPkgMsgButton;

@interface WCCardPkgMsg : NSObject <WCTTableCoding>
{
    _Bool isAutoIncrement;
    _Bool _bNeedCheck;
    _Bool _allUnavailable;
    unsigned int localID;
    unsigned int status;
    unsigned int updateTime;
    unsigned int IntRes1;
    unsigned int IntRes2;
    unsigned int msgType;
    unsigned int jumpType;
    unsigned int reportScene;
    unsigned int getLayoutScene;
    unsigned long long svr64ID;
    NSString *contentForDB;
    NSString *cardId;
    NSString *consumedBoxId;
    NSString *StrRes1;
    NSString *StrRes2;
    long long lastInsertedRowID;
    NSString *cardTpId;
    NSString *logoUrl;
    NSString *webUrl;
    NSString *title;
    NSString *desc;
    NSString *msgID;
    WCCardPkgMsgButton *actionBtn;
    WCCardPkgMsgActivity *activity;
    NSMutableArray *acceptItemList;
    NSString *redDotWording;
    NSString *redDotIconUrl;
    NSString *redDotBuff;
    NSString *_msgTipWording;
    NSString *_msgTipIconUrl;
    NSMutableArray *_jumpUrlBtnList;
    NSString *_logoColor;
    NSMutableArray *_unavailableQrCodeList;
}

+ (const list_2812bee2 *)AllProperties;
+ (const struct WCTAnyProperty *)AnyProperty;
+ (const struct WCTProperty *)IntRes1;
+ (const struct WCTProperty *)IntRes2;
+ (void)ParseMsgXML:(id)arg1 ToMsg:(id)arg2;
+ (const struct WCTProperty *)StrRes1;
+ (const struct WCTProperty *)StrRes2;
+ (const struct WCTProperty *)cardId;
+ (const struct WCTProperty *)consumedBoxId;
+ (const struct WCTProperty *)contentForDB;
+ (const struct WCTProperty *)localID;
+ (const struct WCTProperty *)logoColor;
+ (const struct WCTBinding *)objectRelationalMappingForWCDB;
+ (const struct WCTProperty *)status;
+ (const struct WCTProperty *)svr64ID;
+ (const struct WCTProperty *)updateTime;
- (void).cxx_destruct;
@property(nonatomic) unsigned int IntRes1; // @synthesize IntRes1;
@property(nonatomic) unsigned int IntRes2; // @synthesize IntRes2;
@property(retain, nonatomic) NSString *StrRes1; // @synthesize StrRes1;
@property(retain, nonatomic) NSString *StrRes2; // @synthesize StrRes2;
@property(retain, nonatomic) NSMutableArray *acceptItemList; // @synthesize acceptItemList;
@property(retain, nonatomic) WCCardPkgMsgButton *actionBtn; // @synthesize actionBtn;
@property(retain, nonatomic) WCCardPkgMsgActivity *activity; // @synthesize activity;
@property(nonatomic) _Bool allUnavailable; // @synthesize allUnavailable=_allUnavailable;
@property(nonatomic) _Bool bNeedCheck; // @synthesize bNeedCheck=_bNeedCheck;
@property(retain, nonatomic) NSString *cardId; // @synthesize cardId;
@property(retain, nonatomic) NSString *cardTpId; // @synthesize cardTpId;
@property(retain, nonatomic) NSString *consumedBoxId; // @synthesize consumedBoxId;
@property(retain, nonatomic) NSString *contentForDB; // @synthesize contentForDB;
- (void)dealloc;
@property(retain, nonatomic) NSString *desc; // @synthesize desc;
@property(nonatomic) unsigned int getLayoutScene; // @synthesize getLayoutScene;
@property(nonatomic) _Bool isAutoIncrement; // @synthesize isAutoIncrement;
@property(nonatomic) unsigned int jumpType; // @synthesize jumpType;
@property(retain, nonatomic) NSMutableArray *jumpUrlBtnList; // @synthesize jumpUrlBtnList=_jumpUrlBtnList;
@property(nonatomic) long long lastInsertedRowID; // @synthesize lastInsertedRowID;
@property(nonatomic) unsigned int localID; // @synthesize localID;
@property(retain, nonatomic) NSString *logoColor; // @synthesize logoColor=_logoColor;
@property(retain, nonatomic) NSString *logoUrl; // @synthesize logoUrl;
@property(retain, nonatomic) NSString *msgID; // @synthesize msgID;
@property(retain, nonatomic) NSString *msgTipIconUrl; // @synthesize msgTipIconUrl=_msgTipIconUrl;
@property(retain, nonatomic) NSString *msgTipWording; // @synthesize msgTipWording=_msgTipWording;
@property(nonatomic) unsigned int msgType; // @synthesize msgType;
@property(retain, nonatomic) NSString *redDotBuff; // @synthesize redDotBuff;
@property(retain, nonatomic) NSString *redDotIconUrl; // @synthesize redDotIconUrl;
@property(retain, nonatomic) NSString *redDotWording; // @synthesize redDotWording;
@property(nonatomic) unsigned int reportScene; // @synthesize reportScene;
@property(nonatomic) unsigned int status; // @synthesize status;
@property(nonatomic) unsigned long long svr64ID; // @synthesize svr64ID;
@property(retain, nonatomic) NSString *title; // @synthesize title;
@property(retain, nonatomic) NSMutableArray *unavailableQrCodeList; // @synthesize unavailableQrCodeList=_unavailableQrCodeList;
@property(nonatomic) unsigned int updateTime; // @synthesize updateTime;
@property(retain, nonatomic) NSString *webUrl; // @synthesize webUrl;
- (void)setupDataFromDB;

@end

