//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MMCommon/MMService.h>

#import "IClearDataMgrExt-Protocol.h"
#import "MMService-Protocol.h"
#import "PBMessageObserverDelegate-Protocol.h"

@class NSMutableDictionary, NSString, WCCardCDNDownloadHelper;

@interface WCGiftCardMgr : MMService <PBMessageObserverDelegate, IClearDataMgrExt, MMService>
{
    NSMutableDictionary *_successDic;
    NSMutableDictionary *_failureDic;
    WCCardCDNDownloadHelper *_helper;
}

- (void).cxx_destruct;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (void)acceptGiftCardWithBizUin:(unsigned int)arg1 orderId:(id)arg2 chatroomName:(id)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (void)cancelAllGiftCardCgi;
- (void)dealloc;
@property(retain, nonatomic) NSMutableDictionary *failureDic; // @synthesize failureDic=_failureDic;
- (void)getGiftCardWithBizUin:(unsigned int)arg1 orderId:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (void)getPicbyUrl:(id)arg1 aeskey:(id)arg2 length:(unsigned int)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (void)getVideoByUrl:(id)arg1 aesKey:(id)arg2 length:(unsigned int)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (id)giftFilePathByFileName:(id)arg1;
- (id)giftFileTempPathByFileName:(id)arg1;
- (id)handleAccept:(id)arg1;
- (id)handleGiftCard:(id)arg1;
- (id)handlePreAccept:(id)arg1;
@property(retain, nonatomic) WCCardCDNDownloadHelper *helper; // @synthesize helper=_helper;
- (id)init;
- (void)onDiskStorageWarningCleanedSize:(unsigned long long *)arg1;
- (void)onDiskStorageWarningCleanedSize:(unsigned long long *)arg1 subQueue:(id)arg2;
- (void)onServiceInit;
- (void)preAcceptGiftCardWithBizUin:(unsigned int)arg1 orderId:(id)arg2 chatroomName:(id)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
@property(retain, nonatomic) NSMutableDictionary *successDic; // @synthesize successDic=_successDic;
- (id)sourceLocalPath;
- (id)sourceTempPath;
- (void)uploadKVByType:(long long)arg1 orderId:(id)arg2 BizUin:(unsigned int)arg3 giftUserName:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

