//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCListBaseCellView.h"

@class UIView;

@interface WCListPhotoCellView : WCListBaseCellView
{
    UIView *m_imageGridView;
}

+ (double)calculateHeightForRowData:(id)arg1 isFirstOneInsection:(_Bool)arg2 isLastOneInSection:(_Bool)arg3;
- (void).cxx_destruct;
- (void)handleClickImageView:(id)arg1;
- (void)initImageGridView;
- (void)initView;
- (void)setHighlightedColor;
- (void)setNormalColor;
- (_Bool)shouldOpenNewLineAtY:(double)arg1 withLineHeight:(double)arg2 richTextView:(id)arg3;

@end

