//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class CgiF2FQrcodeResp, NSString;

@protocol WCPayF2FQrcodeCgiDelegate <NSObject>
- (void)onGetF2FQrcode:(CgiF2FQrcodeResp *)arg1;
- (void)onGetF2FQrcodeError:(long long)arg1 errorMsg:(NSString *)arg2;
@end

