//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface WCPayOfflinePayMessageStruct : NSObject
{
    unsigned int m_uiMessageType;
    NSString *m_nsMessageDesc;
}

- (void).cxx_destruct;
- (void)dealloc;
@property(retain, nonatomic) NSString *m_nsMessageDesc; // @synthesize m_nsMessageDesc;
@property(nonatomic) unsigned int m_uiMessageType; // @synthesize m_uiMessageType;

@end

