//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCPayBaseViewController.h"

@class GetRealnameWordingRsp, NSString;
@protocol WCPaySelectVerifyTypeViewControllerDelegate;

@interface WCPaySelectVerifyTypeViewController : WCPayBaseViewController
{
    id <WCPaySelectVerifyTypeViewControllerDelegate> m_delegate;
    NSString *bindCardTitle;
    NSString *bindCardSubTitle;
    NSString *bindIdTitle;
    NSString *bindIdSubTitle;
    NSString *extralWording;
    _Bool questionAnswerSwitch;
    NSString *questionAnswerUrl;
    _Bool isShowBindCard;
    _Bool isShowRealnameVerify;
    _Bool isShowBindCardVerify;
    NSString *bindCardVerifyTitle;
    NSString *bindCardVerifySubTitle;
    _Bool isNeedShowBindCardVerifyAlertView;
    NSString *bindCardVeifyAlertViewRightButtonText;
    NSString *bindCardVeifyAlertViewContent;
    GetRealnameWordingRsp *_wording;
}

- (void).cxx_destruct;
- (void)OnBack;
- (id)createDotLabel;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)getWording;
- (id)headerView;
- (id)init;
- (void)initNavigationBar;
- (void)makeSelectBindCardCell:(id)arg1;
- (void)makeSelectBindCardVerifyCell:(id)arg1;
- (void)makeSelectRealnameVerifyCell:(id)arg1;
- (void)onRightBarButtonClick;
- (void)populateData:(id)arg1;
- (void)reloadTableView;
- (void)selectBindCard;
- (void)selectBindCardVerify;
- (void)selectRealnameVerify;
- (void)setDelegate:(id)arg1;
@property(retain, nonatomic) GetRealnameWordingRsp *wording; // @synthesize wording=_wording;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;

@end

