//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "WNNoteItemProtocol-Protocol.h"

@class FavDataItemWrap, MsgRecordDataWrap, NSString;

@interface WNNoteFavItemBase : NSObject <WNNoteItemProtocol>
{
    int type;
    unsigned int dataSize;
    NSString *localEditorId;
    NSString *originXML;
    FavDataItemWrap *_favWrap;
    MsgRecordDataWrap *_msgWrap;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned int dataSize; // @synthesize dataSize;
@property(retain, nonatomic) FavDataItemWrap *favWrap; // @synthesize favWrap=_favWrap;
@property(retain, nonatomic) NSString *localEditorId; // @synthesize localEditorId;
@property(retain, nonatomic) MsgRecordDataWrap *msgWrap; // @synthesize msgWrap=_msgWrap;
@property(retain, nonatomic) NSString *originXML; // @synthesize originXML;
@property(nonatomic) int type; // @synthesize type;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

