//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSURL;

@interface wnTxtUrlData : NSObject
{
    NSURL *url;
    struct _NSRange range;
}

- (void).cxx_destruct;
@property(nonatomic) struct _NSRange range; // @synthesize range;
@property(retain, nonatomic) NSURL *url; // @synthesize url;

@end

