//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, NSURL;

@interface AppCommentItem : NSObject
{
    int buttonIndex;
    NSString *caption;
    NSString *reportid;
    NSURL *commenturl;
    NSString *itemType;
}

- (void).cxx_destruct;
@property(nonatomic) int buttonIndex; // @synthesize buttonIndex;
@property(retain, nonatomic) NSString *caption; // @synthesize caption;
@property(retain, nonatomic) NSURL *commenturl; // @synthesize commenturl;
- (void)dealloc;
- (id)description;
- (_Bool)isCancelButton;
@property(retain, nonatomic) NSString *itemType; // @synthesize itemType;
@property(retain, nonatomic) NSString *reportid; // @synthesize reportid;

@end

