//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MMCommon/WXPBGeneratedMessage.h>

@class NSString;

@interface BusinessPOIItem : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSString *average; // @dynamic average;
@property(retain, nonatomic) NSString *detailInfo; // @dynamic detailInfo;
@property(nonatomic) unsigned int poiflag; // @dynamic poiflag;
@property(retain, nonatomic) NSString *position; // @dynamic position;
@property(nonatomic) unsigned int starLevel; // @dynamic starLevel;
@property(retain, nonatomic) NSString *title; // @dynamic title;
@property(retain, nonatomic) NSString *url; // @dynamic url;

@end

