//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class CMMDB;

@interface CMessageDB : NSObject
{
    CMMDB *m_oMMDB;
}

- (void).cxx_destruct;
- (_Bool)AddBackupMessageToChatExt:(id)arg1 MsgWrap:(id)arg2;
- (void)AddBackupMsg:(id)arg1 MsgWrap:(id)arg2;
- (void)AddHelloMsg:(id)arg1 MsgWrap:(id)arg2 HelloUser:(id)arg3 OpCode:(unsigned int)arg4 DES:(unsigned int)arg5 checkCreateTime:(_Bool)arg6 status:(unsigned int)arg7;
- (_Bool)AddMessageToChatExt:(id)arg1 MsgWrap:(id)arg2;
- (void)AddMsg:(id)arg1 MsgWrap:(id)arg2;
- (void)AddMsg:(id)arg1 MsgWrap:(id)arg2 withTimeFixed:(_Bool)arg3;
- (void)AutoEmptyTrashTable;
- (_Bool)ClearHelloUnRead:(id)arg1 HelloUser:(id)arg2;
- (_Bool)ClearUnRead:(id)arg1 FromID:(unsigned int)arg2 ToID:(unsigned int)arg3;
- (void)ClearUnReadForSync:(id)arg1 CreateTime:(unsigned int)arg2;
- (void)DelAllMsgs:(id)arg1;
- (void)DelHelloMsg:(id)arg1 HelloUser:(id)arg2;
- (void)DelMsg:(id)arg1 MsgList:(id)arg2 DelAll:(_Bool)arg3;
- (void)DelMsgForBatchDelete:(id)arg1 MsgList:(id)arg2;
- (void)DelOverTimeNewBizMessageOnType:(unsigned int)arg1;
- (void)DropChatTable:(id)arg1;
- (void)EmptyTrashTable;
- (unsigned int)GetAllMesCount:(id)arg1;
- (id)GetAppMsgList:(id)arg1 AfterID:(unsigned int)arg2 CreateTime:(unsigned int)arg3 Limit:(int)arg4;
- (id)GetAppMsgList:(id)arg1 FromID:(unsigned int)arg2 CreateTime:(unsigned int)arg3 Limit:(int)arg4;
- (id)GetAppMsgList:(id)arg1 FromID:(unsigned int)arg2 CreateTime:(unsigned int)arg3 Limit:(int)arg4 Where:(struct WCTExpr)arg5;
- (unsigned int)GetCountInHello:(id)arg1;
- (id)GetDBHelloUsers:(id)arg1 Limit:(int)arg2 OnlyUnread:(_Bool)arg3;
- (id)GetDownMsg:(id)arg1 FromID:(unsigned int)arg2 Limit:(int)arg3;
- (id)GetDownMsgByCreateTime:(id)arg1 FromID:(unsigned int)arg2 FromCreateTime:(unsigned int)arg3 Limit:(int)arg4 LeftCount:(unsigned int *)arg5;
- (id)GetFirstUnreadMsg:(id)arg1;
- (id)GetFirstUnreadMsgIncludingNewXML:(id)arg1;
- (id)GetHelloMsg:(id)arg1 HelloUser:(id)arg2 Limit:(int)arg3 OnlyTo:(_Bool)arg4;
- (id)GetHelloMsg:(id)arg1 Where:(const struct WCTExpr *)arg2 Order:(const list_02de7622 *)arg3 Limit:(int)arg4;
- (id)GetHelloMsgForSyncRead:(id)arg1 Where:(const struct WCTExpr *)arg2;
- (id)GetHelloUsers:(id)arg1 Limit:(int)arg2 OnlyUnread:(_Bool)arg3;
- (id)GetImgAndVideoMsgList:(id)arg1;
- (id)GetImgLastMsg:(id)arg1;
- (id)GetImgLastMsg:(id)arg1 FromID:(unsigned int)arg2 Limit:(int)arg3 CreateTime:(unsigned int)arg4;
- (unsigned int)GetImgMsgCount:(id)arg1;
- (unsigned int)GetImgMsgCount:(id)arg1 FromID:(unsigned int)arg2 CreateTime:(unsigned int)arg3;
- (id)GetImgMsgList:(id)arg1;
- (id)GetImgNextMsg:(id)arg1 FromID:(unsigned int)arg2 Limit:(int)arg3 CreateTime:(unsigned int)arg4;
- (id)GetImgOrVideoLastMsg:(id)arg1;
- (unsigned int)GetImgOrVideoMsgCount:(id)arg1;
- (unsigned int)GetImgOrVideoMsgCount:(id)arg1 FromID:(unsigned int)arg2 CreateTime:(unsigned int)arg3;
- (id)GetImgOrVideoOrAppLastMsg:(id)arg1 FromID:(unsigned int)arg2 Limit:(int)arg3 CreateTime:(unsigned int)arg4;
- (id)GetImgOrVideoOrAppLastMsg:(id)arg1 StartCreateTime:(unsigned int)arg2 EndCreateTime:(unsigned int)arg3 Limit:(int)arg4 needFullMessage:(_Bool)arg5;
- (unsigned int)GetImgOrVideoOrAppMsgMinCreateTime:(id)arg1;
- (id)GetImgOrVideoOrAppNextMsg:(id)arg1 FromID:(unsigned int)arg2 Limit:(int)arg3 CreateTime:(unsigned int)arg4;
- (id)GetImgOrVideoOrAppNextMsg:(id)arg1 StartCreateTime:(unsigned int)arg2 EndCreateTime:(unsigned int)arg3 Limit:(int)arg4 needFullMessage:(_Bool)arg5;
- (id)GetLastInsertMsg:(id)arg1;
- (id)GetLastMsg:(id)arg1;
- (id)GetLastMsgFromUsr:(id)arg1;
- (id)GetLastMsgToUsr:(id)arg1;
- (id)GetLastVoipMsg:(id)arg1 AfterTime:(unsigned int)arg2;
- (id)GetLocalUsrName:(id)arg1;
- (unsigned int)GetMaxCreateTimeInMessage:(id)arg1;
- (unsigned int)GetMesCount:(id)arg1 MesType:(unsigned int)arg2;
- (unsigned int)GetMinCreateTimeInMessage:(id)arg1;
- (id)GetMsg:(id)arg1 BizMsgClientID:(id)arg2;
- (id)GetMsg:(id)arg1 FromID:(unsigned int)arg2 Limit:(int)arg3;
- (id)GetMsg:(id)arg1 LocalID:(unsigned int)arg2;
- (id)GetMsg:(id)arg1 LocalID:(unsigned int)arg2 hasError:(_Bool *)arg3;
- (id)GetMsg:(id)arg1 Where:(const struct WCTExpr *)arg2 order:(const list_02de7622 *)arg3 Limit:(int)arg4;
- (id)GetMsg:(id)arg1 Where:(const struct WCTExpr *)arg2 order:(const list_02de7622 *)arg3 Limit:(int)arg4 hasError:(_Bool *)arg5;
- (id)GetMsg:(id)arg1 n64SvrID:(long long)arg2;
- (id)GetMsgByCreateTime:(id)arg1 FromID:(unsigned int)arg2 FromCreateTime:(unsigned int)arg3 Limit:(int)arg4 LeftCount:(unsigned int *)arg5;
- (id)GetMsgByCreateTime:(id)arg1 FromID:(unsigned int)arg2 FromCreateTime:(unsigned int)arg3 Limit:(int)arg4 LeftCount:(unsigned int *)arg5 FromSequence:(unsigned int)arg6;
- (id)GetMsgForFlowWall:(id)arg1 Where:(const struct WCTExpr *)arg2 Order:(const list_02de7622 *)arg3 Limit:(int)arg4;
- (id)GetMsgForSimple:(id)arg1 Where:(const struct WCTExpr *)arg2 order:(const list_02de7622 *)arg3 Limit:(int)arg4 hasError:(_Bool *)arg5;
- (id)GetMsgForSyncRead:(id)arg1 Where:(const struct WCTExpr *)arg2;
- (id)GetRevokeMessage:(long long)arg1;
- (unsigned int)GetSayHelloStatus:(id)arg1 LocalID:(unsigned int)arg2;
- (id)GetTextMsg:(id)arg1 FromID:(unsigned int)arg2 Limit:(int)arg3;
- (id)GetTextMsg:(id)arg1 FromID:(unsigned int)arg2 ToID:(unsigned int)arg3;
- (unsigned int)GetTextMsgCount:(id)arg1 FromID:(unsigned int)arg2 ToID:(unsigned int)arg3;
- (unsigned int)GetUnReadCount:(id)arg1;
- (unsigned int)GetUnReadCount:(id)arg1 CreateTimeLargerThan:(unsigned int)arg2;
- (unsigned int)GetUnReadCountInHello:(id)arg1;
- (unsigned int)GetValidNewBizMsgCountByChatName:(id)arg1 bizType:(unsigned int)arg2;
- (void)HandleMessage:(id)arg1 ChatName:(id)arg2 Des:(unsigned int)arg3;
- (void)InitDB:(id)arg1;
- (_Bool)InsertRevokeMessage:(id)arg1;
- (void)ModBizMsg:(id)arg1 bizId:(id)arg2 bizStatus:(unsigned int)arg3 bizType:(unsigned int)arg4;
- (void)ModLocationMsg:(id)arg1 MsgWrap:(id)arg2;
- (void)ModMsg:(id)arg1 MsgWrap:(id)arg2;
- (void)ModMsgByBitSet:(id)arg1 MsgWrap:(id)arg2 BitSet:(unsigned int)arg3;
- (void)ModVoipMsgStatus:(id)arg1 MsgWrap:(id)arg2;
- (id)QueryMsgByCreateTime:(id)arg1 FromID:(unsigned int)arg2 FromCreateTime:(unsigned int)arg3 Limit:(int)arg4 Where:(const struct WCTExpr *)arg5;
- (_Bool)RemoveOldRevokeMessagesBefore:(unsigned int)arg1;
- (_Bool)SetSayHelloStatus:(id)arg1 LocalID:(unsigned int)arg2 Status:(unsigned int)arg3;
- (void)TransferMsgFromChatToDuplicate:(id)arg1;
- (void)UpdateMessage:(id)arg1 MsgWrap:(id)arg2;
- (void)UpdateVideoMessage:(id)arg1 MsgWrap:(id)arg2;
- (void)UpdateVoiceMessage:(id)arg1 MsgWrap:(id)arg2;
- (void)UpdateVoiceStatus:(id)arg1 LocalID:(unsigned int)arg2 DownloadStatus:(unsigned int)arg3;
- (_Bool)addMessageToNewWCPayBizExtTable:(id)arg1;
- (_Bool)addMessageToNewWCPayBizExtTable:(id)arg1 type:(int)arg2;
- (_Bool)addMessageToWCPayBizExtTable:(id)arg1;
- (_Bool)beginTransaction;
- (_Bool)commitTransaction;
- (void)fillDBMsg:(id)arg1 andProperty:(list_2812bee2 *)arg2 fromMsgWrap:(id)arg3 des:(unsigned int)arg4;
- (id)getImageMsg:(id)arg1 beforeCreateTime:(unsigned int)arg2 limit:(int)arg3;
- (id)getImageMsg:(id)arg1 limit:(int)arg2;
- (id)getMessageWrapArray:(id)arg1 bizId:(id)arg2;
- (id)getMessageWrapArray:(id)arg1 bizId:(id)arg2 onType:(unsigned int)arg3;
- (_Bool)hasMsg:(id)arg1 fromCreateTime:(unsigned int)arg2 endTime:(unsigned int)arg3;
- (id)init;
- (_Bool)isMessageExist:(id)arg1 MsgSvrId:(long long)arg2;
@property(retain, nonatomic) CMMDB *m_oMMDB; // @synthesize m_oMMDB;
- (const list_02de7622 *)orderOfAscCreateTimeAndMsgLocalId;
- (const list_02de7622 *)orderOfDescCreateTimeAndMsgLocalId;
- (_Bool)rollbackTransaction;
- (_Bool)runTransaction:(CDUnknownBlockType)arg1;
- (_Bool)runTransaction:(CDUnknownBlockType)arg1 event:(CDUnknownBlockType)arg2;
- (void)setMessageUnreadCondition:(struct WCTExpr *)arg1;
- (void)setMessageUnreadCondition:(struct WCTExpr *)arg1 from:(unsigned int)arg2;
- (void)setMessageUnreadConditionIncludingNewXML:(struct WCTExpr *)arg1;

@end

