//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "WCTTableCoding-Protocol.h"

@class NSData, NSString;

@interface CUploadVoiceWrap : NSObject <WCTTableCoding>
{
    NSString *m_nsFromUsrName;
    NSString *m_nsToUsrName;
    long long m_n64SvrID;
    unsigned int m_uiLocalID;
    unsigned int m_uiOffset;
    unsigned int m_uiLen;
    unsigned int m_uiCreateTime;
    unsigned int m_uiVoiceLen;
    unsigned int m_uiVoiceTime;
    unsigned int m_uiVoiceFormat;
    unsigned int m_uiEndFlag;
    NSData *m_dtVoice;
    unsigned int m_uiRetryCount;
    unsigned int m_uiInsertQueueTime;
    unsigned int m_uiCancelFlag;
    unsigned int m_uiVoiceForwardFlag;
    unsigned int m_uiCgi;
    NSString *m_nsMsgThumbUrl;
    NSString *m_nsMsgSource;
    unsigned int m_uiStatus;
    NSString *m_nsExtend;
    NSString *ConStrRes2;
    NSString *ConStrRes3;
}

+ (const list_2812bee2 *)AllProperties;
+ (const struct WCTAnyProperty *)AnyProperty;
+ (const struct WCTProperty *)ConStrRes2;
+ (const struct WCTProperty *)ConStrRes3;
+ (const struct WCTProperty *)m_n64SvrID;
+ (const struct WCTProperty *)m_nsExtend;
+ (const struct WCTProperty *)m_nsToUsrName;
+ (const struct WCTProperty *)m_uiCancelFlag;
+ (const struct WCTProperty *)m_uiCreateTime;
+ (const struct WCTProperty *)m_uiEndFlag;
+ (const struct WCTProperty *)m_uiInsertQueueTime;
+ (const struct WCTProperty *)m_uiLen;
+ (const struct WCTProperty *)m_uiLocalID;
+ (const struct WCTProperty *)m_uiOffset;
+ (const struct WCTProperty *)m_uiRetryCount;
+ (const struct WCTProperty *)m_uiStatus;
+ (const struct WCTProperty *)m_uiVoiceFormat;
+ (const struct WCTProperty *)m_uiVoiceTime;
+ (const struct WCTBinding *)objectRelationalMappingForWCDB;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *ConStrRes2; // @synthesize ConStrRes2;
@property(retain, nonatomic) NSString *ConStrRes3; // @synthesize ConStrRes3;
- (id)description;
- (id)init;
@property(retain, nonatomic) NSData *m_dtVoice; // @synthesize m_dtVoice;
@property(nonatomic) long long m_n64SvrID; // @synthesize m_n64SvrID;
@property(retain, nonatomic) NSString *m_nsExtend; // @synthesize m_nsExtend;
@property(retain, nonatomic) NSString *m_nsFromUsrName; // @synthesize m_nsFromUsrName;
@property(retain, nonatomic) NSString *m_nsMsgSource; // @synthesize m_nsMsgSource;
@property(retain, nonatomic) NSString *m_nsToUsrName; // @synthesize m_nsToUsrName;
@property(nonatomic) unsigned int m_uiCancelFlag; // @synthesize m_uiCancelFlag;
@property(nonatomic) unsigned int m_uiCgi; // @synthesize m_uiCgi;
@property(nonatomic) unsigned int m_uiCreateTime; // @synthesize m_uiCreateTime;
@property(nonatomic) unsigned int m_uiEndFlag; // @synthesize m_uiEndFlag;
@property(nonatomic) unsigned int m_uiInsertQueueTime; // @synthesize m_uiInsertQueueTime;
@property(nonatomic) unsigned int m_uiLen; // @synthesize m_uiLen;
@property(nonatomic) unsigned int m_uiLocalID; // @synthesize m_uiLocalID;
@property(nonatomic) unsigned int m_uiOffset; // @synthesize m_uiOffset;
@property(nonatomic) unsigned int m_uiRetryCount; // @synthesize m_uiRetryCount;
@property(nonatomic) unsigned int m_uiStatus; // @synthesize m_uiStatus;
@property(nonatomic) unsigned int m_uiVoiceFormat; // @synthesize m_uiVoiceFormat;
@property(nonatomic) unsigned int m_uiVoiceForwardFlag; // @synthesize m_uiVoiceForwardFlag;
@property(nonatomic) unsigned int m_uiVoiceLen; // @synthesize m_uiVoiceLen;
@property(nonatomic) unsigned int m_uiVoiceTime; // @synthesize m_uiVoiceTime;

// Remaining properties
@property(nonatomic) _Bool isAutoIncrement;
@property(nonatomic) long long lastInsertedRowID;

@end

