//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIView.h"

@class NSArray, UIImage, UIImageView, UIView;
@protocol EditImageColorSquareBarDelegate;

@interface EditImageColorSquareBar : MMUIView
{
    NSArray *_colorArr;
    double _colorBarIndividualWidth;
    UIView *_selectDotView;
    long long _colorIndex;
    UIImage *_colorImage;
    UIImageView *_selectStatusView;
    _Bool _bShowSelectStatus;
    id <EditImageColorSquareBarDelegate> _m_delegate;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool bShowSelectStatus; // @synthesize bShowSelectStatus=_bShowSelectStatus;
- (void)hideSelectStatusView;
- (void)initView;
- (id)initWithFrame:(struct CGRect)arg1 withDelegate:(id)arg2 withDefaultColorIndex:(long long)arg3;
@property(nonatomic) __weak id <EditImageColorSquareBarDelegate> m_delegate; // @synthesize m_delegate=_m_delegate;
- (void)onClickColorButton:(id)arg1;
- (void)reloadView;
- (void)reloadView2;
- (void)setColorSqaureWithIndex:(long long)arg1 withAnimation:(_Bool)arg2 inEndPhase:(_Bool)arg3;
- (void)setColorSquare:(id)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)setSelectColor:(long long)arg1;
- (void)setSelectColorPosition:(double)arg1 withColorIndex:(long long)arg2 withAnimation:(_Bool)arg3 inEndPhase:(_Bool)arg4;

@end

