//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMBaseSessionInfo.h"

#import "WCTTableCoding-Protocol.h"

@class NSString;

@interface EnterpriseSessionInfo : MMBaseSessionInfo <WCTTableCoding>
{
    unsigned int atMeCount;
    unsigned int newUnreadCount;
    unsigned int newAtMeCount;
    unsigned int sessionTopTime;
    unsigned int lastExposeTime;
    unsigned int chatType;
    NSString *_brandUserName;
}

+ (const list_2812bee2 *)AllProperties;
+ (const struct WCTAnyProperty *)AnyProperty;
+ (const struct WCTProperty *)atMeCount;
+ (const struct WCTProperty *)draftMsg;
+ (const struct WCTProperty *)draftMsgTime;
+ (const struct WCTProperty *)lastExposeTime;
+ (const struct WCTProperty *)lastMsgUpdateTime;
+ (const struct WCTProperty *)newAtMeCount;
+ (const struct WCTProperty *)newUnreadCount;
+ (const struct WCTBinding *)objectRelationalMappingForWCDB;
+ (const struct WCTProperty *)sessionFlag;
+ (const struct WCTProperty *)sessionId;
+ (id)sessionInfoWithContact:(id)arg1 lastMessage:(id)arg2 Brand:(id)arg3;
+ (const struct WCTProperty *)sessionTopTime;
+ (const struct WCTProperty *)unreadCount;
- (void).cxx_destruct;
- (unsigned int)GetUnReadCount:(id)arg1;
@property(nonatomic) unsigned int atMeCount; // @synthesize atMeCount;
@property(retain, nonatomic) NSString *brandUserName; // @synthesize brandUserName=_brandUserName;
@property(nonatomic) unsigned int chatType; // @synthesize chatType;
- (void)checkExposeTime:(unsigned int)arg1;
- (void)clearAtMeCount;
- (void)clearNewAtMeCount;
- (void)clearNewUnreadCount;
- (void)clearUnreadCount;
- (id)contact;
- (void)fixCount;
- (id)genContact;
- (id)genLastMessage;
- (void)incAtMeCount;
- (void)incNewAtMeCount;
- (void)incNewUnreadCount;
- (void)incUnreadCount;
- (id)initWithContact:(id)arg1 lastMessage:(id)arg2 Brand:(id)arg3;
- (_Bool)isSessionTop;
@property(nonatomic) unsigned int lastExposeTime; // @synthesize lastExposeTime;
- (id)lastMessage;
@property(nonatomic) unsigned int newAtMeCount; // @synthesize newAtMeCount;
@property(nonatomic) unsigned int newUnreadCount; // @synthesize newUnreadCount;
- (unsigned int)sessionTopTime;
- (void)setSessionTopTime:(unsigned int)arg1;
- (void)updateContact;
- (void)updateContactAndDraft;
- (_Bool)updateContactAndTopTime;
- (void)updateExposeTime;
- (void)updateLastMessage;
- (void)updateNewUnreadCount;
- (void)updateUnreadCount;

// Remaining properties
@property(nonatomic) _Bool isAutoIncrement;
@property(nonatomic) long long lastInsertedRowID;

@end

