//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MMCommon/WXPBGeneratedMessage.h>

@class FeedsInfo;

@interface Feeds : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) FeedsInfo *feedsInfo; // @dynamic feedsInfo;
@property(nonatomic) unsigned int hotPlayType; // @dynamic hotPlayType;
@property(nonatomic) _Bool showNearest; // @dynamic showNearest;

@end

