//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MMCommon/MMObject.h>

@interface GameCenterUtil : MMObject
{
}

+ (unsigned long long)actionTypeForGame:(id)arg1;
+ (id)badgeFileNameWithLevel:(unsigned int)arg1;
+ (id)getAllGameListDataPath;
+ (id)getClassifyNewGameListCachePath:(id)arg1;
+ (id)getContactDisplayName:(id)arg1;
+ (id)getDefaultImage;
+ (id)getGameAdsCountryInfoFilePath;
+ (id)getGameAdsFilePath;
+ (id)getGameCenterWebViewController:(_Bool)arg1 EntryScene:(id)arg2 Url:(id)arg3;
+ (id)getGameCenterWebViewController:(id)arg1 Url:(id)arg2;
+ (id)getGameMsgGiftInfoFilePath;
+ (id)getGameSearchRecommendItemCachePath;
+ (id)getGameSettingCachePath;
+ (id)getLibraryGameListCachePath;
+ (id)getMoreGameListCachePath;
+ (id)getTopBannerFrom:(id)arg1;
+ (id)getUserCommonDataDir;
+ (id)getUserDataDir;
+ (id)getUserGameDetailFilePath:(id)arg1;
+ (id)getUserGlobalSettingDataPath;
+ (id)getUserGlobalSettingFetchInfoPath;
+ (id)getUserHomeDataPathV4;
+ (id)getUserSubscribeDataPath;
+ (id)parseHomepageDataWithResp:(id)arg1;
+ (id)parseUrlQuery:(id)arg1;
+ (_Bool)shouldUseHVAppInfo:(int)arg1 AppId:(id)arg2;
+ (unsigned int)tagTypeWithString:(id)arg1;
+ (long long)trendTypeWithString:(id)arg1;
+ (id)trimmedStringWithString:(id)arg1;

@end

