//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class UIImageView, UILabel;

@interface LBSErrorViewController : UIViewController
{
    UILabel *errorMessageLabel;
    UIImageView *m_errorImage;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UILabel *errorMessageLabel; // @synthesize errorMessageLabel;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)setErrorMessage:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewDidUnload;

@end

