//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class UIView;

@interface MMCustomHighlightColorButton : UIButton
{
    UIView *_maskView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIView *maskView; // @synthesize maskView=_maskView;
- (void)setHighlightMaskViewColor:(id)arg1 cornerRadius:(double)arg2;
- (void)setHighlighted:(_Bool)arg1;

@end

