//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MMDiskUsageConfig;

@interface MMDiskUsageConfigHandler : NSObject
{
    MMDiskUsageConfig *m_config;
}

- (void).cxx_destruct;
- (void)ConfigWithXml:(id)arg1;
- (id)init;
- (void)loadConfigData;
@property(retain, nonatomic) MMDiskUsageConfig *m_config; // @synthesize m_config;
- (_Bool)readBasicConfigFromXml:(id)arg1 configNode:(struct XmlReaderNode_t *)arg2;
- (void)readMoreConfigFromXml:(id)arg1 configNode:(struct XmlReaderNode_t *)arg2;
- (_Bool)readUnsignedIntNode:(const char *)arg1 rootNode:(struct XmlReaderNode_t *)arg2 xml:(id)arg3 getValue:(unsigned int *)arg4;
- (void)saveConfigData;

@end

