//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIImageView.h"

@protocol imageViewDelegate;

@interface MMImageView : MMUIImageView
{
    id <imageViewDelegate> m_delegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <imageViewDelegate> m_delegate; // @synthesize m_delegate;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;

@end

