//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SKStoreProductViewControllerDelegate-Protocol.h"

@class NSString, SKStoreProductViewController, UIViewController;

@interface MMProductController : NSObject <SKStoreProductViewControllerDelegate>
{
    NSString *productId;
    NSString *callbackUrl;
    UIViewController *pushViewController;
    SKStoreProductViewController *_productViewController;
}

+ (void)dismissProductController;
+ (_Bool)isAvailable;
+ (id)sharedControllerWithProductId:(id)arg1 callbackUrl:(id)arg2;
- (void).cxx_destruct;
@property(copy) NSString *callbackUrl; // @synthesize callbackUrl;
- (id)initWithProductId:(id)arg1 callbackUrl:(id)arg2;
@property(copy) NSString *productId; // @synthesize productId;
@property(retain) SKStoreProductViewController *productViewController; // @synthesize productViewController=_productViewController;
- (void)productViewControllerDidFinish:(id)arg1;
@property(retain) UIViewController *pushViewController; // @synthesize pushViewController;
- (void)showInViewController:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

