//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "PBCoding-Protocol.h"

@class NSString;

@interface MsgPreloadVideoRecord : NSObject <PBCoding>
{
    NSString *m_nsChatName;
    unsigned int m_uiLocalID;
    unsigned int m_uiAccessTime;
    unsigned int m_uiHasPreloadSize;
}

+ (void)initialize;
- (void).cxx_destruct;
- (const map_490096f0 *)getValueTagIndexMap;
- (id)getValueTypeTable;
- (_Bool)isChatRoom;
@property(retain, nonatomic) NSString *m_nsChatName; // @synthesize m_nsChatName;
@property(nonatomic) unsigned int m_uiAccessTime; // @synthesize m_uiAccessTime;
@property(nonatomic) unsigned int m_uiHasPreloadSize; // @synthesize m_uiHasPreloadSize;
@property(nonatomic) unsigned int m_uiLocalID; // @synthesize m_uiLocalID;
- (id)pathForPreloadVideo;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

