//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseScanLogicController.h"

#import "CameraScannerStatusExt-Protocol.h"
#import "OCRTransScannerDelegate-Protocol.h"

@class NSString, OCRTransScanner;

@interface OCRTransLogicController : BaseScanLogicController <OCRTransScannerDelegate, CameraScannerStatusExt>
{
    OCRTransScanner *_scanner;
    NSString *_orign;
    NSString *_translation;
}

- (void).cxx_destruct;
- (void)dealloc;
- (float)getDescriptionLabelTopPadding;
- (id)getDescriptionText;
- (struct CGRect)getDrawCropRect;
- (id)getInfoLabelColor;
- (id)getInfoLabelFont;
- (float)getInfoLabelTopPadding;
- (id)getInfoText;
- (id)init;
- (void)onCameraScannerViewDidInit;
- (void)onGotOCRResultOrign:(id)arg1 Translation:(id)arg2;
- (void)onOCRTransError:(int)arg1;
- (void)onRotate;
- (void)onSendDataLength:(unsigned int)arg1;
- (void)setCropRect;
- (_Bool)shouldStartScanAnimation;
- (void)startScan;
- (void)stopScan;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

