//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class POPAnimation;

@protocol POPAnimationDelegate <NSObject>

@optional
- (void)pop_animationDidApply:(POPAnimation *)arg1;
- (void)pop_animationDidReachToValue:(POPAnimation *)arg1;
- (void)pop_animationDidStart:(POPAnimation *)arg1;
- (void)pop_animationDidStop:(POPAnimation *)arg1 finished:(_Bool)arg2;
@end

