//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;

@protocol PublicWifiPCLogicDelegate <NSObject>
- (void)didGetPcFrontPage:(NSString *)arg1 headimg:(NSString *)arg2;
- (void)didNetWorkError:(NSString *)arg1 errMsg:(NSString *)arg2;
- (void)didSetUserInfo;
@end

