//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSString;

@interface PushMailContact : NSObject <NSCopying>
{
    NSString *nsContactName;
    NSString *nsContactAddress;
}

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)init;
@property(retain, nonatomic) NSString *nsContactAddress; // @synthesize nsContactAddress;
@property(retain, nonatomic) NSString *nsContactName; // @synthesize nsContactName;

@end

