//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@interface ShakeInfo : NSObject <NSCoding>
{
    unsigned int m_uiShakeTimes;
    unsigned int m_uiBackGroundImgID;
}

- (void)encodeWithCoder:(id)arg1;
- (id)init;
- (id)initWithCoder:(id)arg1;
@property(nonatomic) unsigned int m_uiBackGroundImgID; // @synthesize m_uiBackGroundImgID;
@property(nonatomic) unsigned int m_uiShakeTimes; // @synthesize m_uiShakeTimes;
- (void)preInit;

@end

