//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIView.h"

#import "IWCCardPkgExt-Protocol.h"
#import "LuckyCoinAnimationControllerDelegate-Protocol.h"
#import "WCNewCardDetailViewControllerDelegate-Protocol.h"

@class LuckyCoinAnimationController, NSString, ShakeCardData, WCCardData;
@protocol ShakeCardDetailViewDelegate;

@interface ShakeCardDetailView : MMUIView <IWCCardPkgExt, WCNewCardDetailViewControllerDelegate, LuckyCoinAnimationControllerDelegate>
{
    ShakeCardData *_shakeCardData;
    WCCardData *_wcCardData;
    _Bool _isNormalType;
    LuckyCoinAnimationController *_emojiController;
    id <ShakeCardDetailViewDelegate> viewDelegate;
}

- (void).cxx_destruct;
- (void)dealloc;
- (void)didAnimationFinish;
- (id)genAcceptCardSuccView:(struct CGRect)arg1;
- (id)genGetCardView:(struct CGRect)arg1;
- (id)getAcceptCardBtnTitle;
- (id)getBackgroundImage;
- (id)getBottomBtn;
- (id)getCloseBtn;
- (id)getReceivedIcon;
- (id)getShakeCardData;
- (id)getViewController;
- (void)hiddenAcceptFailLabel;
- (void)hiddenAllView;
- (void)hiddenCardDetailView;
- (void)initView;
- (id)initWithCardData:(id)arg1 withFrame:(struct CGRect)arg2;
- (_Bool)isShowingAcceptCardView;
- (void)layoutSubviews;
- (void)onAcceptCard:(id)arg1 ErrCode:(int)arg2 ErrMsg:(id)arg3;
- (void)onClickAcceptBtn:(id)arg1;
- (void)onClickViewCardDetail:(id)arg1;
- (void)onGiftCard:(id)arg1 lastIndex:(id)arg2;
- (void)onSingleTap:(id)arg1;
- (void)onUseCard:(id)arg1;
- (void)onWCCardDetailViewControllerCancel:(id)arg1;
- (void)onWCCardUpdate:(id)arg1;
@property(nonatomic) __weak id <ShakeCardDetailViewDelegate> viewDelegate; // @synthesize viewDelegate;
- (void)showAcceptCardView;
- (void)showAcceptFailLabel:(id)arg1;
- (void)showAcceptSuccView;
- (void)showGetCardView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

