//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UINavigationController.h>

@interface UINavigationController (LogicController)
- (id)DispatchPopViewControllerAnimated:(_Bool)arg1;
- (id)FindViewControllerBefore:(id)arg1;
- (void)PopNavStackIfNeed;
- (id)PopToRootViewControllerAnimated:(_Bool)arg1;
- (id)PopToViewController:(id)arg1 animated:(_Bool)arg2;
- (id)PopViewControllerAnimated:(_Bool)arg1;
- (void)PopViewControllerCount:(unsigned int)arg1 animated:(_Bool)arg2;
- (_Bool)PushToNavStackIfNeed:(id)arg1 operationType:(long long)arg2 bAnimated:(_Bool)arg3;
- (void)PushViewController:(id)arg1 animated:(_Bool)arg2;
- (double)abtestDelayTime;
- (void)clearPopNavStack;
- (id)getNextTopViewController;
- (id)getTopViewController;
- (id)getViewControllerImage:(id)arg1;
- (id)interactivePopGestureRecognizer_internal;
- (_Bool)isCurrentViewController;
- (_Bool)isNavStackLocked;
- (_Bool)isUseNavStackLock;
- (void)lockNavStack;
@property(nonatomic) _Bool m_bAnimated;
- (void)onBackButtonClicked:(id)arg1;
- (void)pushLogicController:(id)arg1 animated:(_Bool)arg2;
- (void)pushUniqueClassViewController:(id)arg1 animated:(_Bool)arg2;
- (void)unlockNavStack;
@end

