//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class MMTableView, NSString, UILabel;
@protocol VoiceSearchContactsViewDelegate;

@interface VoiceSearchContactsViewController : MMUIViewController <UITableViewDelegate, UITableViewDataSource>
{
    _Bool m_hasResults;
    MMTableView *m_tableView;
    UILabel *m_emptyLabelView;
    _Bool m_isFirstControl;
    unsigned int m_voiceID;
    NSString *m_errorLabelTextString;
    id <VoiceSearchContactsViewDelegate> m_voiceSearchContactsViewDelegate;
}

- (void).cxx_destruct;
- (void)backToPreView:(id)arg1;
- (void)didAppear;
- (id)initByResults:(_Bool)arg1;
- (void)initTableView;
- (void)loadView;
@property(nonatomic) __weak id <VoiceSearchContactsViewDelegate> m_voiceSearchContactsViewDelegate; // @synthesize m_voiceSearchContactsViewDelegate;
- (void)onTopBarFrameChanged;
- (void)setErrorLabelViewText:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidBePoped:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)willAppear;
- (void)willDisappear;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

