//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "WCTTableCoding-Protocol.h"

@class NSData, NSString;

@interface WAConfigInfo : NSObject <WCTTableCoding>
{
    unsigned int type;
    unsigned int version;
    unsigned int updateTime;
    NSString *appID;
    NSData *configData;
}

+ (const list_2812bee2 *)AllProperties;
+ (const struct WCTAnyProperty *)AnyProperty;
+ (const struct WCTProperty *)appID;
+ (const struct WCTProperty *)configData;
+ (const struct WCTBinding *)objectRelationalMappingForWCDB;
+ (const struct WCTProperty *)type;
+ (const struct WCTProperty *)updateTime;
+ (const struct WCTProperty *)version;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *appID; // @synthesize appID;
@property(retain, nonatomic) NSData *configData; // @synthesize configData;
@property(nonatomic) unsigned int type; // @synthesize type;
@property(nonatomic) unsigned int updateTime; // @synthesize updateTime;
@property(nonatomic) unsigned int version; // @synthesize version;

// Remaining properties
@property(nonatomic) _Bool isAutoIncrement;
@property(nonatomic) long long lastInsertedRowID;

@end

