//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WARefreshFooter.h"

@interface WARefreshAutoFooter : WARefreshFooter
{
    _Bool _automaticallyRefresh;
    double _triggerAutomaticallyRefreshPercent;
}

@property(nonatomic, getter=isAutomaticallyRefresh) _Bool automaticallyRefresh; // @synthesize automaticallyRefresh=_automaticallyRefresh;
- (void)prepare;
- (void)scrollViewContentOffsetDidChange:(id)arg1;
- (void)scrollViewContentSizeDidChange:(id)arg1;
- (void)scrollViewPanStateDidChange:(id)arg1;
- (void)setHidden:(_Bool)arg1;
- (void)setState:(long long)arg1;
@property(nonatomic) double triggerAutomaticallyRefreshPercent; // @synthesize triggerAutomaticallyRefreshPercent=_triggerAutomaticallyRefreshPercent;
- (void)willMoveToSuperview:(id)arg1;

@end

