//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MMCommon/MMObject.h>

@class WAShowOutInfo;

@interface WAShowOutLogic : MMObject
{
    WAShowOutInfo *_showOutInfo;
}

- (void).cxx_destruct;
- (id)fetchLocalShowOutData;
- (void)getShowOutDataWithCompletion:(CDUnknownBlockType)arg1;
@property(retain, nonatomic) WAShowOutInfo *showOutInfo; // @synthesize showOutInfo=_showOutInfo;
- (void)startFetchRemoteShowOutData;

@end

