//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSMutableDictionary;

@protocol WCAccountAlertUploadAddressbookViewControllerDelegate <NSObject>
- (void)onAlertUploadAddressbookMore;
- (void)onEnableUploadAddressbookEnable:(NSMutableDictionary *)arg1 dicEmailInfo:(NSMutableDictionary *)arg2;
- (void)onEnableUploadAddressbookSkip;
@end

