//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCAccountBaseViewController.h"

#import "ILinkEventExt-Protocol.h"
#import "IMMLanguageMgrExt-Protocol.h"

@class NSString, UIButton, UIImageView, UIView;
@protocol WCAccountLoginFirstViewControllerDelegate;

@interface WCAccountLoginFirstViewController : WCAccountBaseViewController <ILinkEventExt, IMMLanguageMgrExt>
{
    id <WCAccountLoginFirstViewControllerDelegate> m_delegate;
    UIView *m_view;
    UIView *m_bottomView;
    UIButton *m_regBtn;
    UIButton *m_loginBtn;
    UIButton *m_btnChangeLanguage;
    UIImageView *m_backgroundImageView;
}

- (void).cxx_destruct;
- (void)adjustTableViewRect;
- (void)adjustViewAndNavBarRect;
- (void)dealloc;
- (void)didRotateFromInterfaceOrientation:(long long)arg1;
- (id)getBackgroundImgWithOrientation:(long long)arg1;
- (double)getVisibleHeight;
- (id)init;
- (void)initView;
- (void)onChangeLanguage;
- (void)onLanguageChange;
- (void)setDelegate:(id)arg1;
- (void)updateChangeLanguageBtn;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

