//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCCanvasComponent.h"

#import "WCCanvasDynamicDataLoaderDelegate-Protocol.h"
#import "WCCanvasImageLoaderObserver-Protocol.h"

@class NSString, UIButton, WCCanvasDynamicDataLoader;

@interface WCCanvasButtonComponent : WCCanvasComponent <WCCanvasImageLoaderObserver, WCCanvasDynamicDataLoaderDelegate>
{
    UIButton *_button;
    WCCanvasDynamicDataLoader *_dataLoader;
}

+ (struct CGSize)calcSizeForCanvasItem:(id)arg1 dataItem:(id)arg2 orientation:(long long)arg3;
- (void).cxx_destruct;
- (void)ImageDidFail:(id)arg1;
- (void)ImageDidLoad:(id)arg1 Url:(id)arg2;
@property(retain, nonatomic) UIButton *button; // @synthesize button=_button;
- (void)configureWithCanvasItem:(id)arg1 dataItem:(id)arg2 orientation:(long long)arg3;
@property(retain, nonatomic) WCCanvasDynamicDataLoader *dataLoader; // @synthesize dataLoader=_dataLoader;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)onCanvasDynamicXMLReturn:(id)arg1 error:(int)arg2;
- (void)onClickButton:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

