//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSMutableArray;

@interface WCRedEnvelopesRewardInfo : NSObject <NSCoding>
{
    NSMutableArray *arrRewardItem;
    unsigned int resoureId;
    unsigned int reportId;
    unsigned int reportKey;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *arrRewardItem; // @synthesize arrRewardItem;
- (void)encodeWithCoder:(id)arg1;
- (_Bool)hasRewardForMe;
- (id)init;
- (id)initWithCoder:(id)arg1;
@property(nonatomic) unsigned int reportId; // @synthesize reportId;
@property(nonatomic) unsigned int reportKey; // @synthesize reportKey;
@property(nonatomic) unsigned int resoureId; // @synthesize resoureId;

@end

