//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MMCommon/MMObject.h>

#import "PBMessageObserverDelegate-Protocol.h"

@class NSString;
@protocol WCDataProviderDelegate;

@interface WCTimelineDataProvider : MMObject <PBMessageObserverDelegate>
{
    NSString *fpHash;
    _Bool isWorking;
    unsigned long long uiClientLatestID;
    id <WCDataProviderDelegate> delegate;
}

- (void).cxx_destruct;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (void)SafeMD5;
- (id)converListToList:(id)arg1;
- (id)converServerAdList2List:(id)arg1;
- (id)convertAdvertiseMsgListToList;
- (id)convertServerRecList2List:(id)arg1;
- (void)dealloc;
@property(nonatomic) __weak id <WCDataProviderDelegate> delegate; // @synthesize delegate;
- (void)forceGetSnsTimeLineOfSightFromServer;
- (id)getAdMsgXmlList;
- (id)getCachedAdItemList;
- (int)getNetworkType;
- (_Bool)hasExistAdItem:(id)arg1;
- (id)init;
- (void)internalSaveResponseListForFutureList:(id)arg1;
- (_Bool)isAdItemReceived:(id)arg1;
- (void)meggeObjectOperation:(id)arg1 snsObject:(id)arg2;
- (unsigned int)onServiceCleanCache;
- (unsigned int)onServiceCleanMd5;
- (void)removeAllCacheAdvertiseMsgXml;
- (void)reportKVStatSightRecieveWithMeidaItem:(id)arg1;
- (void)requestForSnsTimeLineRequest:(id)arg1 minID:(id)arg2 lastRequestTime:(unsigned int)arg3;
- (_Bool)responseForSnsTimeLineResponse:(id)arg1 Event:(unsigned int)arg2;
- (void)responseForSnsTimeLineWithTypeResponse:(id)arg1 Event:(unsigned int)arg2;
- (void)saveResponseListForFutureList:(id)arg1;
- (void)updateChangedItemsWithReferID:(id)arg1 bottomID:(id)arg2 minChangedTime:(unsigned int)arg3;
- (void)updateWithReferID:(id)arg1 LatestID:(id)arg2;

@end

