//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WloginTlv.h"

@interface WloginTlv_0x150 : WloginTlv
{
    unsigned int dwBitmap;
    BOOL cNet;
}

@property BOOL cNet; // @synthesize cNet;
- (void)dealloc;
- (int)decode:(char **)arg1 andBuffLen:(int *)arg2;
@property unsigned int dwBitmap; // @synthesize dwBitmap;

@end

