//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UILabel.h>

@class MMTimer, NSArray;

@interface WXGDotDotDotLabel : UILabel
{
    MMTimer *m_animationTimer;
    unsigned long long m_imageIndex;
    NSArray *_wordList;
    double _duration;
}

- (void).cxx_destruct;
- (void)_startAnimations;
- (void)animateforDuration:(double)arg1;
- (void)dealloc;
@property(nonatomic) double duration; // @synthesize duration=_duration;
- (id)initWithFrame:(struct CGRect)arg1;
@property(retain, nonatomic) NSArray *wordList; // @synthesize wordList=_wordList;

@end

